<div class="container">
    <div class="row">
        <div class="col-md-4">
            <h4>Useful Links</h4>
            <ul class="list-sitemap">
                <li><a href="/">Home</a></li>
                <li><a href="/about-us">About Us</a></li>
                <li><a href="/storelocator/">Fitting Locations</a></li>
                <li><a href="/offers">Special Offers</a></li>
                <li><a href="/offers-terms-and-conditions">Offers - Terms and Conditions</a></li>
                <li><a href="/faqs">FAQs</a></li>
                <li><a href="/contact">Contact Us</a></li>
                <li><a href="/monthly-installments-plan">Monthly Installments Plan</a></li>
                <li><a href="/terms-and-conditions">Temrs and Conditions</a></li>
                <li><a href="/privacy-policy">Privacy Policy</a></li>
                <li><a href="/terms-of-sales-and-services">Terms of Sales and Services</a></li>
                <li><a href="/warranty">Warranty</a></li>
                <li><a href="/returns-refunds">Returns/Refund Policy</a></li>
            </ul>
            <h4>Customer Account</h4>
            <ul class="list-sitemap">
                <li><a href="/customer/account/login/">Login</a></li>
                <li><a href="/customer/account/create/">Register</a></li>
                <li><a href="/customer/account/forgotpassword/">Forget Password</a></li>
            </ul>
        </div>
        <div class="col-md-4">
            <h4>Product Category</h4>
            <ul class="list-sitemap">
                <li><a href="/tyres.html">All Car Tyres</a></li>
                    <!--<ul class="list-sitemap">
                        <li><a href="/">Tyre by Brands</a></li>
                        <li><a href="/">Tyre by Size</a></li>
                    </ul>-->
                <li><a href="/motorcycle-tyre.html">Motorcycle Tyres</a></li>
                <li><a href="/car-wheels.html">Car Wheels and Rims</a></li>
                <!-- Add more links as needed -->
            </ul>
            <h4>Car Service</h4>
            <ul class="list-sitemap">
                <li class="insurance">Car Insurance
                    <ul class="list-sitemap">
                        <li><a href="/insurance/index/thirdparty">3rd Party Car Insurance</a></li>
                        <li><a href="/insurance/index/comprehensive">Comprehensive Car Insurance</a></li>
                    </ul>
                </li>
                <li><a href="/urgent-car-services-in-uae">Car Battery</a></li>
                <li><a href="/3m-car-window-tinting-dubai">3M Car Window Tinting</a></li>
                <li><a href="/car-wheels-and-rims">Wheels and Rims</a></li>
                <li><a href="/car-services">Services Package</a></li>
                <!-- Add more links as needed -->
            </ul>
        </div>
        <div class="col-md-4">
            <h4>Blogs</h4>
            <ul class="list-sitemap">
                <li><a href="/blog">All Blogs</a></li>
                <!-- Add more links as needed -->
            </ul>
        </div>
    </div>
</div>
<style>
   ul.list-sitemap {
  list-style-type: disc;
  margin-left: 18px;
}

ul.list-sitemap li {
  color: #4bcf2e;
}

ul.list-sitemap li.insurance {
    color: #000000;
}

</style>