<?php
declare(strict_types=1);
/** @var \Mirasvit\Sorting\Block\DebugInCard $block */

$types = [
    'global' => __('Global Score'),
    'frame1' => __('Sort by'),
    'frame2' => __('Then sort by'),
]
?>
<div class="mst-sorting__debug">
    <p><small><?= $block->escapeHtml($block->getProduct()->getSku()) ?> [id: <?= $block->escapeHtml($block->getProduct()->getId()) ?>]</small></p>

    <?php foreach ($types as $type => $typeName): ?>
        <div class="mst-sorting__debug-score <?= $block->escapeHtmlAttr($type) ?>">
            <span><?= $block->escapeHtml($typeName) ?></span>
            <strong><?= $block->escapeHtml($block->getScore($type)) ?></strong>
        </div>
    <?php endforeach ?>

    <div class="mst-sorting__debug-ranking">
        <?php foreach ($types as $type => $typeName): ?>
            <div class="mst-sorting__debug-score <?= $block->escapeHtmlAttr($type) ?>">
                <span><?= $block->escapeHtml($typeName) ?></span>
                <strong><?= $block->escapeHtml($block->getScore($type)) ?></strong>
            </div>
            <div class="ranking-info">
                <?php foreach ($block->getScores($type) as $name => $score): ?>
                    <div class="ranking">
                        <?php if ($score == "-"): ?>
                            <div style="font-size: 13px;line-height: 16px;text-overflow: ellipsis;overflow: hidden;white-space: nowrap; margin-bottom: 2px;">
                                <?= $block->escapeHtml(__("%1 attribute: %2", ucfirst($name), $block->getProduct()->getData($name))) ?>
                            </div>
                            <?php break; //we use only first attribute for sorting?>
                        <?php else: ?>
                            <?php
                            $values      = $block->getValues($type);
                            $value       = $values[$name];
                            $weights     = $block->getWeights($type);
                            $factorScore = $score * $weights[$name];
                            $width       = abs($score / 100 * 50);
                            if ($width > 50) {
                                $width = 50;
                            }
                            ?>

                            <span><?= $block->escapeHtml($name) ?></span>
                            <strong><?= $block->escapeHtml(number_format((float)$factorScore, 3, '.', ' ')) ?></strong>

                            <div class="score">
                                Score: <?= $block->escapeHtml(number_format((float)$score, 3, '.', ' ')) ?> * <?= $block->escapeHtml($weights[$name]) ?> = <?= $block->escapeHtml(number_format((float)$factorScore, 3, '.', ' ')) ?>
                            </div>

                            <div class="value">
                                Value: <?= $block->escapeHtml($value) ?>
                            </div>
                        <?php endif ?>
                    </div>
                <?php endforeach ?>
            </div>
        <?php endforeach ?>
    </div>
</div>
<?php if ($block->isApplyStyles()): ?>
    <style>
        .mst-sorting__debug {
            position: relative;
            cursor: help;
        }

        .mst-sorting__debug-score {
            border: 1px solid #d6d6d6;
            padding: 5px 10px;
            display: flex;
            color: #777;
            font-size: 1.3rem;
            margin-bottom: -1px;
        }

        .mst-sorting__debug span,
        .mst-sorting__debug strong {
            font-weight: 600;
        }

        .mst-sorting__debug-score strong,
        .mst-sorting__debug-ranking strong {
            margin-left: auto;
            color: #777;
        }

        .mst-sorting__debug-score.global strong {
            color: #ff5b5b;
        }

        .mst-sorting__debug-score.criterion strong {
            color: #e80808;
        }

        .mst-sorting__debug-ranking {
            display: none;
            position: absolute;
            left: 0;
            top: 28px;
            background: #fff;
            border: 1px solid #d6d6d6;
            z-index: 10000;
            width: 100%;
            box-sizing: border-box;
            font-size: 1.2rem;
        }

        .mst-sorting__debug-ranking strong {
            float: right;
        }

        .mst-sorting__debug-ranking .mst-sorting__debug-score {
            border: none;
            border-top: 1px solid #d6d6d6;
        }

        .mst-sorting__debug-ranking .mst-sorting__debug-score:first-child {
            border-top: none;
        }

        .mst-sorting__debug-ranking .ranking-info {
            padding: 0 0 5px 0;
        }

        .mst-sorting__debug-ranking .ranking {
            position: relative;
            color: #777;
            padding: 5px 10px 5px 20px;
        }

        .mst-sorting__debug-ranking .ranking .ranking-name {
            margin-bottom: 5px;
        }

        .mst-sorting__debug-ranking .ranking .value {
            font-size: 10px;
            color: #999;
        }

        .mst-sorting__debug-ranking .ranking .score {
            clear: both;
            font-size: 11px;
            color: #999;
            margin-bottom: 5px;
            margin-top: 5px;
        }

        .mst-sorting__debug-ranking .ranking .ranking-bar {
            position: relative;
            background: #eee;
            height: 5px;
            margin-bottom: 5px;
        }

        .mst-sorting__debug-ranking .ranking .ranking-bar .positive {
            background: #87BC24;
            height: 5px;
            left: 50%;
            top: 0;
            position: absolute;
        }

        .mst-sorting__debug-ranking .ranking .ranking-bar .negative {
            background: #D91A00;
            height: 5px;
            right: 50%;
            top: 0;
            position: absolute;
        }

        .mst-sorting__debug:hover > .mst-sorting__debug-ranking {
            display: block;
        }

        .mst-sorting__debug:hover > .mst-sorting__debug-score {
            display: none;
        }
    </style>
<?php
endif ?>
