<?php
/** @var \Mirasvit\Core\Block\Adminhtml\Cron $block */
$lastExecutedJob = $block->getLastExecutedJob();
?>

<section style="margin-bottom: 2rem;">
    <div class="admin__page-section-item-title"><span class="title"><?= $block->escapeHtml(__('Status')) ?></span></div>

    <table class="table data-table admin__table-secondary">
        <tr>
            <th><?= $block->escapeHtml(__('Server gmt time')) ?></th>
            <td><?= $block->escapeHtml($block->getGmtDateTime()) ?></td>
        </tr>
        <?php if ($lastExecutedJob): ?>
            <tr>
                <th><?= $block->escapeHtml(__('Last job')) ?></th>
                <td><?= $block->escapeHtml($lastExecutedJob->getJobCode()) ?></td>
            </tr>
            <tr>
                <th><?= $block->escapeHtml(__('Executed')) ?></th>
                <td><?= $block->escapeHtml($lastExecutedJob->getExecutedAt()) ?></td>
            </tr>
            <tr>
                <th><?= $block->escapeHtml(__('Status')) ?></th>
                <td><?= $block->escapeHtml($lastExecutedJob->getStatus()) ?></td>
            </tr>
        <?php else: ?>
            <tr>
                <th><?= $block->escapeHtml(__('Last job')) ?></th>
                <td><? $block->escapeHtml(__('none')) ?></td>
            </tr>
        <?php endif ?>
    </table>
</section>

<?php if (!$block->isCronRunning()): ?>
    <section style="margin-bottom: 2rem;">
        <div class="admin__page-section-item-title"><span class="title"><?= $block->escapeHtml(__('Cron setup')) ?></span></div>
        <div class="dashboard-item-content">
            <?= $block->escapeHtml(__(
                'Cron for Magento is not running. To setup a cron job, follow the link %1',
                'http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-cron.html'
            )); ?>
        </div>
    </section>
<?php endif ?>

<section style="margin-bottom: 2rem;">
    <div class="admin__page-section-item-title"><span class="title"><?= $block->escapeHtml(__('Cron Jobs')) ?></span></div>
    <div class="dashboard-item-content"><?= /* @noEscape */ $block->getChildHtml('cronJobs') ?></div>
</section>
