<?php
$sizeblockObj     = $block->getLayout()->createBlock('Hdweb\Tyrefinder\Block\Size');
$vehicleblockObj  = $block->getLayout()->createBlock('Hdweb\Tyrefinder\Block\Vehicle');
$activeCategories = $block->getActiveCatrgory();
$catalogSearchUrl = $block->getCatalogSearchUrl();
?>
<section class="searchSec" id="online-tyre-finder">
    <ul class="nav nav-tabs">
        <li class="nav-item sizetab size active"><a class="nav-link active" href="#tabs-1" data-toggle="tab"><?php echo __('Search By Size') ?></a></li>
        <li class="nav-item vehicletab"><a class="nav-link " href="#tabs-2" data-toggle="tab"><?php echo __('Search By Vehicle') ?></a></li>
    </ul>
    <div class="tab-content">
        <div id="tabs-1" class="tab-pane active" role="tabpanel">
            <form id="finder-size-form" method="get" action="<?php echo $catalogSearchUrl; ?>" name="finder-size-form">
                 <div class="form-group" style="display: none;">
                      <select id="categoryid" name="categoryid" required="" >
                            <?php foreach ($activeCategories as $key => $category) {?>
                               <option data-url="<?php echo $category->getUrl() ?>"
                                value="<?php echo $category->getEntityId() ?>"><?php echo $category->getName() ?></option>
                            <?php }?>
                        </select>
                 </div>   
                <div class="form-group">
                    <!-- <input class="form-control" type="text" placeholder="WIDTH"> -->
                    <a href="javaScript:void(0)" id="frontWidthLabel" class="search_option form-control"><?php echo __('Width') ?></a>
                    <input type="hidden" id="frontWidthLabel-hidden" name="width" required value="" >
                </div>
                <div class="form-group">
                    <!-- <input class="form-control" type="text" placeholder="HEIGHT"> -->
                    <a href="javaScript:void(0)" id="frontHeightLabel"  class="search_option disablesearchoption form-control"><?php echo __('Height') ?></a>
                    <input type="hidden" id="frontHeightLabel-hidden" name="height" required value="" >
                </div>
                <div class="form-group">
                    <!-- <input class="form-control" type="text" placeholder="RIM"> -->
                     <a href="javaScript:void(0)" id="frontRimLabel"  class="search_option disablesearchoption form-control"><?php echo __('Rim') ?></a>
                    <input type="hidden" id="frontRimLabel-hidden" name="rim" required value="" >
                </div>
                <input type="hidden" id="rearWidthLabel-hidden" name="width_rear" value="" >
                <input type="hidden" id="rearHeightLabel-hidden" name="height_rear" value="" >
                <input type="hidden" id="rearRimLabel-hidden" name="rim_rear" value="" >
                <input type="hidden" id="rearWidthLabel-text" value="" >
                <input type="hidden" id="rearHeightLabel-text" value="" >
                <input type="hidden" id="rearRimLabel-text" value="" >
                
                <input class="btn btn-success" type="submit" value="<?php echo __('Search') ?>" id="finder_size_btn">
            </form>
         </div>
        <div id="tabs-2" class="tab-pane" role="tabpanel">
            <form id="finder-vehicle-form" action="<?php echo $catalogSearchUrl; ?>" method="post">
                <input type="hidden" name="homme_search_vehicle" value="1" />
                <div class="form-group">
                    <a href="javaScript:void(0)" id="vehicle_make" class="form-control" ><?php echo __('Make'); ?></a>
                    <input type="hidden"  id="vehicle_make_hidden" name="vehicle_make" value="" required>
                </div>
                <div class="form-group">
                    <a href="javaScript:void(0)" id="vehicle_model" class="form-control"><?php echo __('Model'); ?></a>
                    <input type="hidden"  id="vehicle_model_hidden" name="vehicle_model" value="" required>
                </div>
                <div class="form-group">
                     <a href="javaScript:void(0)" id="vehicle_year" class="form-control"><?php echo __('Year'); ?></a>
                     <input type="hidden"  id="vehicle_year_hidden" name="vehicle_year" value="" required>
                </div>
                <input type="hidden"  id="vehicle_engine_hidden" name="vehicle_engine" value="">
                <input class="btn btn-success tyre_menu_fitting_button mobile-margin" type="submit" value="
                <?php echo __('Search') ?>" id="findvehicle">
                <button class="button" id="submitVehicleForm" type="submit" style="display: none;"></button>
            </form>
        </div>
    </div>
</section>

<?php /*  Search by size Popup start */ ?>
<div id="tyre_finder_modal" class="modal-content tt" style="display: none;">
  <div class="tyreHeader">
                    <a style="display: none;" class="backLink allback backwidth" href="javascript:void(0)" class="back_to_prev" onclick="goback('tyre_finder_modal_front_width_content','backrim','front','Width')"><i class="fa fa-arrow-circle-left"></i> <?php echo __('Back To Width') ?></a>
                    <a style="display: none;" class="backLink allback backprofile" href="javascript:void(0)" class="back_to_prev" onclick="goback('tyre_finder_modal_front_height_content','backwidth','front','Height')"><i class="fa fa-arrow-circle-left"></i> <?php echo __('Back To Height') ?></a>
                    <a style="display: none;" class="backLink allback backrim" href="javascript:void(0)" class="back_to_prev" onclick="goback('tyre_finder_modal_front_rim_content','backprofile','front','Rim')"><i class="fa fa-arrow-circle-left"></i> <?php echo __('Back To Rim') ?></a>
                    <a style="display: none;" class="backLink allback backfromrim" href="javascript:void(0)" class="back_to_prev" onclick="goback('tyre_finder_modal_front_rim_content','backprofile','front','FrontRim')"><i class="fa fa-arrow-circle-left"></i> <?php echo __('Back To Front Rim') ?></a>
                    <a style="display: none;" class="backLink allback rearbackwidth" href="javascript:void(0)" class="back_to_prev" onclick="goback('tyre_finder_modal_rear_width_content','backfromrim','rear','rearWidth')"><i class="fa fa-arrow-circle-left"></i> <?php echo __('Back To Width') ?></a>
                    <a style="display: none;" class="backLink allback rearbackprofile" href="javascript:void(0)" class="back_to_prev" onclick="goback('tyre_finder_modal_rear_height_content','rearbackwidth','rear','rearHeight')"><i class="fa fa-arrow-circle-left"></i> <?php echo __('Back To Height') ?></a>
                    <a style="display: none;" class="backLink allback rearbackrim" href="javascript:void(0)" class="back_to_prev" onclick="goback('tyre_finder_modal_rear_rim_content','rearbackprofile','rear','rearRim')"><i class="fa fa-arrow-circle-left"></i> <?php echo __('Back To Rim') ?></a>
  </div>
    <div class="tyrewidthInfo">
        <div class="tyreInfoLeft">
          <ul class="stepper">
            <li role="presentation" class="active">
              <span><?= __('Width') ?></span>
            </li>
            <li role="presentation" class="">
              <span><?= __('Height') ?></span>
            </li>
            <li role="presentation" class="">
              <span><?= __('Rim Size') ?></span>
            </li>
          </ul>
        </div>  
        <figure class="tyresizes">
          <svg class="tyretext" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
       viewBox="0 0 336.3 77" style="enable-background:new 0 0 336.3 77;" xml:space="preserve">
          <g class="txtcolor active">
                <path d="M25.7,48c1.2,5.4,2.6,10.7,4.1,16c-1.2,0.9-2.4,1.7-3.5,2.6c-3.1-2-6.3-3.9-9.5-5.8c1,3.6,2.1,7.2,3.3,10.7
                  c-1.1,0.9-2.3,1.9-3.4,2.8c-4.8-2.7-9.7-5.3-14.6-7.7c1.1-1,2.3-2,3.5-3c3.4,1.8,6.8,3.7,10.2,5.6c-1.2-3.7-2.3-7.4-3.4-11.2
                  c1.1-0.8,2.1-1.7,3.2-2.5c3.4,2,6.7,4.1,9.9,6.2c-1-3.8-2-7.5-3-11.3C23.5,49.6,24.6,48.8,25.7,48z"/>
                <path  d="M27.3,46.9c-0.6-0.9-0.2-2.2,1.1-3c1.3-0.9,2.6-0.8,3.2,0.1c0.6,1,0.2,2.2-1.1,3.1
                  C29.2,47.9,27.9,47.8,27.3,46.9z M29.7,49.6c1.1-0.8,2.3-1.5,3.4-2.3c2.2,3.3,4.3,6.6,6.5,9.9c-1.1,0.7-2.2,1.4-3.2,2.2
                  C34.1,56.1,31.9,52.9,29.7,49.6z"/>
                <path  d="M46.4,34.1c2.6,4.8,5.3,9.5,7.9,14.3c-1.1,0.6-2.1,1.2-3.2,1.8c-0.2-0.4-0.5-0.8-0.7-1.2
                  c-0.3,1.4-1.3,2.5-2.8,3.4c-3.2,1.9-6.9,1.5-9-1.6c-2-3.1-0.7-6.8,2.7-8.8c1.5-0.9,3-1.2,4.3-0.9c-1-1.7-1.9-3.3-2.9-5
                  C44,35.4,45.2,34.7,46.4,34.1z M48.1,45.1c-1-1.8-3-2.1-4.7-1.1c-1.7,1-2.4,2.9-1.3,4.6c1.1,1.7,3,2,4.7,1
                  C48.4,48.7,49.1,46.8,48.1,45.1z"/>
                <path  d="M65.7,41.8c-0.5,0.8-1.4,1.5-2.5,2.1c-2.8,1.4-5.1,1-6.4-1.5c-0.8-1.4-1.5-2.9-2.3-4.3
                  c-0.6,0.3-1.2,0.7-1.9,1c-0.4-0.8-0.8-1.5-1.3-2.3c0.6-0.3,1.3-0.7,1.9-1c-0.4-0.8-0.9-1.7-1.3-2.5c1.2-0.6,2.4-1.3,3.6-1.9
                  c0.4,0.9,0.9,1.7,1.3,2.6c1-0.5,2.1-1,3.1-1.5c0.4,0.8,0.8,1.6,1.2,2.4c-1,0.5-2,1-3.1,1.5c0.7,1.4,1.5,2.9,2.2,4.3
                  c0.5,0.9,1.3,1.1,2.2,0.6c0.5-0.3,1-0.6,1.2-1.1C64.4,40.6,65,41.2,65.7,41.8z"/>
                <path  d="M77.6,29.6c0.9,2.1,1.7,4.2,2.6,6.3c-1.2,0.5-2.3,1-3.5,1.5c-0.8-1.9-1.6-3.8-2.5-5.7c-0.7-1.8-2-2.2-3.6-1.5
                  c-1.7,0.8-2.6,2.3-1.7,4.2c0.8,1.8,1.6,3.6,2.4,5.3c-1.2,0.5-2.3,1.1-3.5,1.6c-2.3-4.9-4.7-9.8-7-14.7c1.2-0.6,2.5-1.2,3.7-1.7
                  c0.8,1.7,1.6,3.5,2.4,5.2c0.6-1.3,1.8-2.4,3.4-3.1C73.4,25.7,76.3,26.3,77.6,29.6z"/>
          </g>
          <g class="txtcolor">
                <path  d="M129.2,6.2c0.8,5.1,1.7,10.1,2.5,15.2c-1.3,0.2-2.6,0.4-3.8,0.7c-0.4-2.1-0.8-4.1-1.1-6.2
                  c-2.6,0.5-5.2,1-7.7,1.5c0.4,2.1,0.9,4.1,1.3,6.2c-1.3,0.3-2.5,0.6-3.8,0.9c-1.2-5-2.3-10-3.5-15c1.4-0.3,2.7-0.6,4.1-0.9
                  c0.4,2,0.9,4,1.3,5.9c2.6-0.6,5.2-1.1,7.8-1.5c-0.4-2-0.7-4-1.1-6C126.5,6.6,127.8,6.4,129.2,6.2z"/>
                <path  d="M147.5,14.3c-3.3,0.3-6.6,0.7-9.9,1.2c0.6,1.4,2.1,2.1,4,1.9c1.4-0.2,2.3-0.6,3.1-1.5
                  c0.7,0.6,1.5,1.2,2.2,1.8c-1.1,1.4-2.8,2.2-5.1,2.5c-4.4,0.5-7.7-1.5-8.2-5c-0.6-3.5,2.1-6.5,6.3-7c4-0.5,7.3,1.6,7.6,5.3
                  C147.5,13.7,147.5,14.1,147.5,14.3z M137.2,13.5c2.2-0.3,4.3-0.6,6.5-0.8c-0.4-1.5-1.8-2.3-3.5-2.1
                  C138.4,10.9,137.3,12,137.2,13.5z"/>
                <path  d="M148.7,3.7c-0.1-1.1,0.8-2,2.3-2.1c1.5-0.1,2.5,0.6,2.6,1.7c0.1,1.1-0.9,2-2.3,2.2
                  C149.9,5.6,148.8,4.8,148.7,3.7z M149.5,7.2c1.3-0.1,2.6-0.2,3.9-0.3c0.3,3.9,0.5,7.9,0.8,11.8c-1.2,0.1-2.5,0.2-3.7,0.3
                  C150.2,15.1,149.9,11.2,149.5,7.2z"/>
                <path  d="M171.1,6.3c0,3.3,0,6.6,0,9.9c0,4.4-2.6,6.4-7.1,6.5c-2.4,0.1-4.8-0.4-6.3-1.4c0.4-0.8,0.9-1.7,1.3-2.5
                  c1.1,0.8,3,1.2,4.6,1.2c2.6-0.1,3.7-1.2,3.7-3.3c0-0.2,0-0.3,0-0.5c-1,1-2.4,1.5-4.1,1.6c-3.6,0.1-6.6-2-6.8-5.4
                  c-0.2-3.4,2.7-5.9,6.4-6c1.9-0.1,3.5,0.5,4.5,1.6c0-0.5,0-1,0-1.5C168.6,6.3,169.9,6.3,171.1,6.3z M167.3,11.9
                  c0-1.7-1.5-2.9-3.6-2.8c-2,0.1-3.5,1.3-3.4,3c0.1,1.7,1.6,2.8,3.6,2.8C165.9,14.8,167.3,13.6,167.3,11.9z"/>
                <path  d="M188.3,12c-0.2,2.3-0.3,4.5-0.5,6.8c-1.2-0.1-2.5-0.2-3.7-0.2c0.1-2.1,0.2-4.2,0.3-6.2
                  c0.1-1.9-0.8-2.8-2.6-2.9c-1.9-0.1-3.2,0.9-3.3,3.1c-0.1,2-0.1,3.9-0.2,5.9c-1.2,0-2.5-0.1-3.7-0.1c0.1-5.4,0.2-10.9,0.3-16.3
                  c1.3,0,2.7,0.1,4,0.1c-0.1,1.9-0.1,3.8-0.2,5.7c1.1-0.9,2.6-1.3,4.4-1.2C186.2,6.6,188.5,8.4,188.3,12z"/>
                <path  d="M199.6,19.3c-0.8,0.4-2,0.5-3.1,0.4c-3-0.3-4.7-1.9-4.4-4.7c0.1-1.6,0.3-3.2,0.4-4.8
                  c-0.7-0.1-1.4-0.1-2.1-0.2c0.1-0.9,0.1-1.8,0.2-2.6c0.7,0.1,1.4,0.1,2.1,0.2c0.1-1,0.2-1.9,0.2-2.9c1.3,0.1,2.6,0.2,4,0.4
                  c-0.1,1-0.2,1.9-0.3,2.9c1.1,0.1,2.2,0.2,3.4,0.4c-0.1,0.9-0.2,1.7-0.3,2.6c-1.1-0.1-2.2-0.2-3.3-0.4c-0.2,1.6-0.3,3.2-0.5,4.8
                  c-0.1,1,0.4,1.6,1.5,1.7c0.6,0.1,1.1,0,1.6-0.3C199.1,17.6,199.3,18.5,199.6,19.3z"/>
          </g>
          <g class="txtcolor">
                <path  d="M245.7,30.1c-0.6-1.7-1.2-3.4-1.8-5.1c-0.1,0-0.1,0-0.2-0.1c-1.1-0.3-2.2-0.7-3.3-1c-0.4,1.4-0.8,2.7-1.2,4.1
                  c-1.3-0.4-2.5-0.7-3.8-1.1c1.4-4.9,2.8-9.9,4.1-14.8c2.5,0.7,5,1.4,7.5,2.2c4.6,1.4,6.8,4.5,5.6,7.7c-0.8,2.2-2.6,3.3-5,3.5
                  c0.7,2,1.4,3.9,2.1,5.9C248.4,31,247.1,30.6,245.7,30.1z M246,17.1c-1.1-0.3-2.1-0.7-3.2-1c-0.5,1.7-1,3.4-1.5,5.1
                  c1.1,0.3,2.1,0.6,3.2,1c2.4,0.7,3.9,0.2,4.4-1.4C249.3,19.2,248.4,17.8,246,17.1z"/>
                <path  d="M256.9,17.7c0.4-1,1.6-1.5,3-0.9c1.4,0.5,2.1,1.6,1.7,2.6c-0.4,1.1-1.6,1.5-3,1
                  C257.2,19.8,256.5,18.7,256.9,17.7z M256.2,21.2c1.2,0.4,2.5,0.9,3.7,1.4c-1.4,3.7-2.8,7.4-4.2,11.1c-1.2-0.4-2.4-0.9-3.6-1.3
                  C253.5,28.6,254.8,24.9,256.2,21.2z"/>
                <path  d="M282.4,38c-1,2-2,4-3.1,6c-1.1-0.6-2.3-1.1-3.4-1.7c0.9-1.9,1.8-3.7,2.7-5.6c0.8-1.7,0.3-3-1.1-3.6
                  c-1.6-0.8-3.2-0.4-4,1.5c-0.8,1.8-1.7,3.6-2.5,5.4c-1.2-0.5-2.3-1.1-3.5-1.6c0.8-1.9,1.7-3.8,2.5-5.7c0.8-1.8,0.3-2.9-1.2-3.6
                  c-1.6-0.7-3.1-0.2-3.9,1.7c-0.8,1.8-1.5,3.7-2.3,5.5c-1.2-0.5-2.3-1-3.5-1.4c1.4-3.7,2.9-7.3,4.3-11c1.2,0.5,2.4,0.9,3.5,1.4
                  c-0.2,0.4-0.3,0.8-0.5,1.3c1.3-0.5,3-0.4,4.6,0.3c1.8,0.8,3,2,3.4,3.6c1.5-0.6,3.4-0.6,5.3,0.3C282.6,32.2,284,34.8,282.4,38z"/>
                <path  d="M288.4,47.1c0.8-0.6,1.7-1.1,2.5-1.7c0.8,1.6,2.4,3.2,4.2,4.3c2.1,1.2,3.3,1.2,3.8,0.4c1.5-2.5-8.4-6-5.6-11
                  c1.3-2.3,4.5-3,9.1-0.3c2,1.2,3.8,2.9,4.7,4.5c-0.9,0.5-1.7,1.1-2.6,1.6c-1-1.6-2.3-2.8-3.7-3.7c-2.2-1.3-3.4-1.1-3.9-0.2
                  c-1.4,2.4,8.6,6.2,5.5,11c-1.4,2.2-4.6,2.7-8.8,0.1C291.2,50.8,289.2,48.8,288.4,47.1z"/>
                <path  d="M310.1,44.1c0.6-0.9,1.9-1,3.2-0.2c1.3,0.9,1.7,2.1,1.1,3c-0.6,0.9-2,1.1-3.2,0.2
                  C310,46.2,309.5,45,310.1,44.1z M308.6,47.3c1.1,0.7,2.3,1.5,3.4,2.3c-2.2,3.3-4.4,6.5-6.6,9.8c-1.1-0.7-2.2-1.5-3.2-2.2
                  C304.3,53.9,306.4,50.6,308.6,47.3z"/>
                <path  d="M319,66c-0.5,0.7-1.1,1.4-1.6,2.1c-3.2-2.5-6.5-4.9-9.8-7.1c0.4-0.6,0.8-1.1,1.2-1.7c3.3-0.6,6.5-1.2,9.9-1.7
                  c-1.9-1.4-3.8-2.7-5.7-4.1c0.5-0.7,1-1.4,1.5-2.2c3.3,2.3,6.6,4.7,9.9,7.2c-0.4,0.5-0.8,1.1-1.3,1.6c-3.4,0.4-6.7,0.9-9.9,1.5
                  C315.2,63.1,317.1,64.5,319,66z"/>
                <path  d="M332.8,74.4c-2.7-2.3-5.4-4.6-8.1-6.8c-0.6,1.4-0.1,3,1.6,4.4c1.1,0.9,2.2,1.3,3.4,1.4c0.1,1,0.2,1.9,0.3,2.9
                  c-1.8,0.1-3.7-0.7-5.6-2.2c-3.6-3-4.5-6.9-2.3-9.7c2.2-2.8,6.3-2.8,9.7,0c3.3,2.7,4.2,6.6,1.6,9.5C333.3,73.9,333,74.2,332.8,74.4
                  z M325.9,66c1.8,1.5,3.6,2.9,5.3,4.4c0.8-1.3,0.4-2.9-1.1-4.1C328.7,65.1,327.1,65,325.9,66z"/>
          </g>
         </svg>
         <div class="tyreValue">
          <span class="tvalue_1 valuetxt active"><?= __('165') ?></span>
          <span class="tvalue_2 valuetxt"><?= __('/') ?></span>
          <span class="tvalue_3 valuetxt"><?= __('55') ?></span>
          <span class="tvalue_4 valuetxt"><?= __('r16') ?></span>
         </div>
          <!-- <img src="/../media/popup-half-tyre.png" alt=""> -->
        </figure>
    </div>
    <div id="tyre_finder_modal_wrapper" class="">
      <div class="tyreinfoResult">
            <div class="tyreselection">
                <label class="selectiontitle"><?php echo __('Current Selection: ')?></label>
                <strong class="data-selected selectiondata"></strong>
            </div>
            <div class="rear-tyre-selection" style="display: none;">
                <label class="rearselectiontitle"><?php echo __('Rear Tyre Selection: ')?></label> 
                <strong class="data-selected rearselectiondata"></strong>
            </div>
           <?php /* <div class="reset-size-selection" style="display: none;">
             <a href="javascript:void(0)" class="resetbtn resetSize" onclick="resetselection()">
              <?php echo __('Reset')?>
            </a> 
          </div> */ ?>
            <!-- <a href="javascript:void(0)" class="resetbtn" onclick="resetvehicleselection()">reset</a> -->
          </div>
        <div class="searchloader" data-role="loader" style="display: none;">
            <div class="loader">
              <img alt="Loading..." src="<?php echo $this->getViewFileUrl('images/logo-white.png'); ?>"><p>
               <?php echo __('Please wait...') ?></p>
            </div>
        </div>
               <ul class="tyre_finder_modal_front_width_content tyre_finder_allcontent" >
                    <?php foreach ($sizeblockObj->gehomeTytWidthOptions() as $v): ?>
                        <li>
                            <a href="javascript:void(0)" title="<?php echo $v['label'] ?>" onclick="getheight('<?php echo $v['value'] ?>','<?php echo $v['label'] ?>','front')" id ="front-width-<?php echo $v['value'] ?>"><?php echo $v['label'] ?></a>
                            </li>
                    <?php endforeach;?>
                </ul>
    </div>
</div>
<div class="tyre_finder_modal_front_width_wrapper" style="display: none;">
                        <?php foreach ($sizeblockObj->gehomeTytWidthOptions() as $v): ?>
                            <li>
                                <a href="javascript:void(0)" title="<?php echo $v['label'] ?>" onclick="getheight('<?php echo $v['value'] ?>','<?php echo $v['label'] ?>','front')" id ="front-width-<?php echo $v['value'] ?>"><?php echo $v['label'] ?></a>
                                </li>
                        <?php endforeach;?>
</div>
<div class="tyre_finder_modal_rear_width_wrapper" style="display: none;">
                        <?php foreach ($sizeblockObj->gehomeTytWidthOptions() as $v): ?>
                            <li>
                                <a href="javascript:void(0)" title="<?php echo $v['label'] ?>" onclick="getRearheight('<?php echo $v['value'] ?>','<?php echo $v['label'] ?>','rear')" id ="rear-width-<?php echo $v['value'] ?>"><?php echo $v['label'] ?></a>
                                </li>
                        <?php endforeach;?>
</div>
<div id="tyre_finder_modal_front_submittyreselection" class="" style="display: none;">
            <div  id="" class="">
                <div class="diiferent_rear_tyre">
                   <span  class="reartyrelink"><?php echo __('Click here to choose different rear tyre?') ?></span>
                </div>
                <div class="">
                    <button class="button find primary" onclick="submitTyreSelection()"><?php echo __('Search Tyres') ?></button>
               </div>
            </div>
</div>
<div id="tyre_finder_modal_rear_submittyreselection" class="" style="display: none;">
                <div class="">
                    <button class="button find primary" onclick="submitTyreSelection()"><?php echo __('Search Tyres') ?></button>
               </div>
</div>
<?php /*  Search by size Popup end */ ?>


<?php /*  Search by vehicle Popup start */ ?>
<div id="vehicle_finder_modal" class="modal-content" style="display: none;">
  <div class="tyreHeader">
    <a href="" class="backLink">

                        <a style="display: none;" href="javascript:void(0)" class="backLink vehicleallbackbutton vehiclebackmake" onclick="vehcilegoback('vehicle_finder_modal_make_content','no','vehiclemakeimage','Make')">
                            <i class="fa fa-arrow-circle-left"></i> <?php echo __('Back to Make') ?>
                        </a>
                        <a  style="display: none;" href="javascript:void(0)" class="backLink vehicleallbackbutton vehiclebackmodel" onclick="vehcilegoback('vehicle_finder_modal_model_content','vehiclebackmake','vehiclemodelimage','Model')">
                            <i class="fa fa-arrow-circle-left"></i> <?php echo __('Back to Model') ?>
                        </a>
                        <a style="display: none;" href="javascript:void(0)" class="backLink vehicleallbackbutton vehiclebackyear" onclick="vehcilegoback('vehicle_finder_modal_year_content','vehiclebackmodel','vehicleyearimage','Year')">
                            <i class="fa fa-arrow-circle-left"></i> <?php echo __('Back to Year') ?>
                        </a>
                        <a style="display: none;" href="javascript:void(0)" class="backLink vehicleallbackbutton vehiclebackengine" onclick="vehcilegoback('vehicle_finder_modal_engine_content','vehiclebackyear','vehicleyearimage','Tyre Size')">
                            <i class="fa fa-arrow-circle-left"></i> <?php echo __('Back to Tyre Size') ?>
                        </a>

  </div>
    <div class="tyrewidthInfo">
        <div class="tyreInfoLeft">
          <ul class="stepper vehiclestepper">
            <li role="presentation" class="make active">
              <span><?= __('Make') ?></span>
            </li>
            <li role="presentation" class="model ">
              <span><?= __('Model') ?></span>
            </li>
            <li role="presentation" class="year ">
              <span><?= __('Year') ?></span>
            </li>
            <li role="presentation" class="engine ">
              <span><?= __('Tyre Size') ?></span>
            </li>            
          </ul>
        </div>  
 
    </div>
     <div id="vehicle_finder_modal_wrapper" class="">
      <div class="tyreinfoResult">
            <div class="tyreselection">
                <label class="vehicleselectiontitle"><?php echo __('Current Selection: ')?></label>
                <strong class="vehicleselectiondata"></strong>
            </div>
                    <?php /* <div class="reset-vehicle-selection" style="display: none;">
                        <a href="javascript:void(0)" class="resetbtn" onclick="resetvehicleselection()">
                          <?php echo __('Reset') ?>
                        </a>
                    </div>  */ ?>          
          </div>
        <div class="searchloader" data-role="loader" style="display: none;">
            <div class="loader">
              <img alt="Loading..." src="<?php echo $this->getViewFileUrl('images/logo-white.png'); ?>"><p>
               <?php echo __('Please wait...') ?></p>
            </div>
        </div> 
               <ul class="vehicle_finder_modal_make_content vehicle_finder_modal_allcontent" >
                    <?php foreach ($vehicleblockObj->getVehilceMake() as $make): ?>
                        <li>
                            <a href="javascript:void(0)" title="<?php echo $make['name_en'] ?>" onclick="getmodel('<?php echo $make['slug'] ?>','<?php echo $make['name_en'] ?>')" id ="make-<?php echo $make['slug'] ?>"><?php echo $make['name_en'] ?></a>
                            </li>
                    <?php endforeach;?>
                </ul>
    </div>
</div>
<?php /*  Search by vehicle Popup end */ ?>

<script type="text/javascript">
var getHeightUrl = '<?php echo $sizeblockObj->getActionUrl('getheight'); ?>';
var getRimUrl = '<?php echo $sizeblockObj->getActionUrl('getrim'); ?>';
var getCategoryWidthUrl = '<?php echo $sizeblockObj->getActionUrl('getcategorywidth'); ?>';
var getModelUrl = '<?php echo $sizeblockObj->getActionUrl('getmodel'); ?>';
var getyearUrl = '<?php echo $sizeblockObj->getActionUrl('getyear'); ?>';
var getengineUrl = '<?php echo $sizeblockObj->getActionUrl('getengine'); ?>';
</script>
 <script type="text/x-magento-init">
        {
            "*": {
                "tyrefinder": {}
            }
        }
 </script>
