<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Sales\Block\Adminhtml\Order\View\Info $block
 */
$order = $block->getOrder();
$helper = $this->helper('Hdweb\Installer\Helper\Data');
$coreHelper = $this->helper('Hdweb\Core\Helper\Data');
$baseCurrencyCode = (string)$order->getBaseCurrencyCode();
$globalCurrencyCode = (string)$order->getGlobalCurrencyCode();
$orderCurrencyCode = (string)$order->getOrderCurrencyCode();

$orderAdminDate = $block->formatDate(
    $block->getOrderAdminDate($order->getCreatedAt()),
    \IntlDateFormatter::MEDIUM,
    true
);

$orderStoreDate = $block->formatDate(
    $order->getCreatedAt(),
    \IntlDateFormatter::MEDIUM,
    true,
    $block->getTimezoneForStore($order->getStore())
);

$customerUrl = $block->getCustomerViewUrl();

$allowedAddressHtmlTags = ['b', 'br', 'em', 'i', 'li', 'ol', 'p', 'strong', 'sub', 'sup', 'ul'];

$customerEmail=$order->getCustomerEmail();

$objectManager=\Magento\Framework\App\ObjectManager::getInstance();
?>

<section class="admin__page-section order-view-account-information">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('Order & Account Information')) ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-information">
            <?php /* Order Information */ ?>
            <?php $confirmationEmailStatusMessage = $order->getEmailSent() ? __('The order confirmation email was sent') : __('The order confirmation email is not sent'); ?>
            <div class="admin__page-section-item-title">
                <span class="title">
                    <?php if ($block->getNoUseOrderLink()) : ?>
                        <?= $block->escapeHtml(__('Order # %1', $order->getRealOrderId())) ?> (<span><?= $block->escapeHtml($confirmationEmailStatusMessage) ?></span>)
                    <?php else : ?>
                        <a href="<?= $block->escapeUrl($block->getViewUrl($order->getId())) ?>"><?= $block->escapeHtml(__('Order # %1', $order->getRealOrderId())) ?></a>
                        <span>(<?= $block->escapeHtml($confirmationEmailStatusMessage) ?>)</span>
                    <?php endif; ?>
                </span>
            </div>
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-information-table">
                <tr>
                    <th><?= $block->escapeHtml(__('Order Date')) ?></th>
                    <td><?= $block->escapeHtml($orderAdminDate) ?></td>
                </tr>
                <?php if ($orderAdminDate != $orderStoreDate) : ?>
                    <tr>
                        <th><?= $block->escapeHtml(__('Order Date (%1)', $block->getTimezoneForStore($order->getStore()))) ?></th>
                        <td><?= $block->escapeHtml($orderStoreDate) ?></td>
                    </tr>
                <?php endif;?>
                <tr>
                    <th><?= $block->escapeHtml(__('Order Status')) ?></th>
                    <td><span id="order_status"><?= $block->escapeHtml($order->getStatusLabel()) ?></span></td>
                </tr>
                <?= $block->getChildHtml() ?>
                <?php if ($block->isSingleStoreMode() == false) : ?>
                    <tr>
                        <th><?= $block->escapeHtml(__('Purchased From')) ?></th>
                        <td><?= $block->escapeHtml($block->getOrderStoreName(), ['br']) ?></td>
                    </tr>
                <?php endif; ?>
                <?php if ($order->getRelationChildId()) : ?>
                    <tr>
                        <th><?= $block->escapeHtml(__('Link to the New Order')) ?></th>
                        <td>
                            <a href="<?= $block->escapeUrl($block->getViewUrl($order->getRelationChildId())) ?>">
                                <?= $block->escapeHtml($order->getRelationChildRealId()) ?>
                            </a>
                        </td>
                    </tr>
                <?php endif; ?>
                <?php if ($order->getRelationParentId()) : ?>
                    <tr>
                        <th><?= $block->escapeHtml(__('Link to the Previous Order')) ?></th>
                        <td>
                            <a href="<?= $block->escapeUrl($block->getViewUrl($order->getRelationParentId())) ?>">
                                <?= $block->escapeHtml($order->getRelationParentRealId()) ?>
                            </a>
                        </td>
                    </tr>
                <?php endif; ?>
                <?php if ($order->getRemoteIp() && $block->shouldDisplayCustomerIp()) : ?>
                    <tr>
                        <th><?= $block->escapeHtml(__('Placed from IP')) ?></th>
                        <td><?= $block->escapeHtml($order->getRemoteIp()); ?><?= $order->getXForwardedFor() ? ' (' . $block->escapeHtml($order->getXForwardedFor()) . ')' : ''; ?></td>
                    </tr>
                <?php endif; ?>
                <?php if ($order->getSalesPersonId() ): 
                      $userFactory=$objectManager->get('Magento\User\Model\UserFactory');
                      $user = $userFactory->create()->load($order->getSalesPersonId());
                      $Firstname = $user->getFirstname();
                      $Lastname = $user->getLastname()
                     ?>
                        <tr>
                            <th><?php echo $block->escapeHtml(__('Salesperson')) ?></th>
                            <td><?php echo $block->escapeHtml($Firstname.' '.$Lastname);
                   
                        ?></td>
                        </tr>
                    <?php endif; ?>

                <?php if ($globalCurrencyCode !== $baseCurrencyCode) : ?>
                    <tr>
                        <th><?= $block->escapeHtml(__('%1 / %2 rate:', $globalCurrencyCode, $baseCurrencyCode)) ?></th>
                        <td><?= $block->escapeHtml($order->getBaseToGlobalRate()) ?></td>
                    </tr>
                <?php endif; ?>
                <?php if ($baseCurrencyCode !== $orderCurrencyCode && $globalCurrencyCode !== $orderCurrencyCode) : ?>
                    <tr>
                        <th><?= $block->escapeHtml(__('%1 / %2 rate:', $orderCurrencyCode, $baseCurrencyCode)) ?></th>
                        <td><?= $block->escapeHtml($order->getBaseToOrderRate()) ?></td>
                    </tr>
                <?php endif; ?>
            </table>
            </div>
        </div>

        <div class="admin__page-section-item order-account-information">
            <?php /* Account Information */ ?>
            <div class="admin__page-section-item-title">
                <span class="title"><?= $block->escapeHtml(__('Account Information')) ?></span>
                <div class="actions">
                    <?php if ($customerUrl) : ?>
                        <a href="<?= /* @noEscape */ $customerUrl ?>" target="_blank">
                            <?= $block->escapeHtml(__('Edit Customer')) ?>
                        </a>
                    <?php endif; ?>
                </div>
            </div>
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-account-information-table">
                    <tr>
                        <th><?= $block->escapeHtml(__('Customer Name')) ?></th>
                        <td>
                            <?php if ($customerUrl) : ?>
                                <a href="<?= $block->escapeUrl($customerUrl) ?>" target="_blank">
                                    <span><?= $block->escapeHtml($order->getCustomerName()) ?></span>
                                </a>
                            <?php else : ?>
                                <?= $block->escapeHtml($order->getCustomerName()) ?>
                            <?php endif; ?>
                        </td>
                    </tr>
                    <tr>
                        <th><?= $block->escapeHtml(__('Email')) ?></th>
                        <td><a href="mailto:<?= $block->escapeHtmlAttr($order->getCustomerEmail()) ?>"><?= $block->escapeHtml($order->getCustomerEmail()) ?></a></td>
                    </tr>
                    <?php if ($groupName = $block->getCustomerGroupName()) : ?>
                        <tr>
                            <th><?= $block->escapeHtml(__('Customer Group')) ?></th>
                            <td><?= $block->escapeHtml($groupName) ?></td>
                        </tr>
                    <?php endif; ?>
                    <?php foreach ($block->getCustomerAccountData() as $data) : ?>
                        <tr>
                            <th><?= $block->escapeHtml($data['label']) ?></th>
                            <td><?= $block->escapeHtml($data['value'], ['br']) ?></td>
                        </tr>
                    <?php endforeach;?>
                    <?= $block->getChildHtml('extra_customer_info') ?>
                </table>
            </div>
        </div>
    </div>
</section>

<section class="admin__page-section order-addresses">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('Address Information')) ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-billing-address">
            <?php /* Billing Address */ ?>
            <div class="admin__page-section-item-title">
                <span class="title"><?= $block->escapeHtml(__('Billing Address')) ?></span>
                <div class="actions"><?= /* @noEscape */ $block->getAddressEditLink($order->getBillingAddress()); ?></div>
            </div>
            <address class="admin__page-section-item-content"><?= $block->escapeHtml($block->getFormattedAddress($order->getBillingAddress()), $allowedAddressHtmlTags); ?></address>
        </div>
        <?php if (!$block->getOrder()->getIsVirtual()) : ?>
            <div class="admin__page-section-item order-shipping-address">
                <?php /* Shipping Address */ ?>
                <div class="admin__page-section-item-title">
                    <span class="title"><?= $block->escapeHtml(__('Shipping Address')) ?></span>
                    <div class="actions"><?= /* @noEscape */ $block->getAddressEditLink($order->getShippingAddress()); ?></div>
                </div>
                <address class="admin__page-section-item-content"><?= $block->escapeHtml($block->getFormattedAddress($order->getShippingAddress()), $allowedAddressHtmlTags); ?></address>
            </div>
        <?php endif; ?>
    </div>
</section>

<?php
$make=$order->getMake();
if(isset($make)){ ?>
    <section class="admin__page-section order-vehicle">
        <div class="admin__page-section-title">
            <span class="title"><?php echo $block->escapeHtml(__('Vehicle Information')) ?></span>
        </div>
        <div>
            
            <div class="field">
                <span class="lable_field"><?php echo __('Plate No :')?></span><span class="text_field"><?php echo $order->getPlate() ?> </div>
            <div class="field">
                <span class="lable_field"><?php echo __('Make :') ?> </span><span class="text_field"><?php echo $order->getMake() ; ?></span> 
            </div>
            <div class="field">
                <span class="lable_field"><?php echo __('Model :') ?></span><span class="text_field"><?php echo $order->getModel(); ?></span> 
            </div>
            <div class="field">
                <span class="lable_field"><?php echo __('Year :') ?> </span><span class="text_field"><?php echo $order->getYear() ; ?></span> 
            </div>
            <div class="actions"><a href="JavaScript:Void(0);" id="vehicleData"><?php echo __('Edit')?></a></div>
        </div>
    </section>
<?php }else{ ?>
    <section class="admin__page-section order-vehicle">
        <div class="admin__page-section-title">
            <span class="title"><?php echo $block->escapeHtml(__('Vehicle Information')) ?></span>
        </div>
        <div>
            <div class="actions"><a href="JavaScript:Void(0);" id="vehicleData"><?php echo __('Add Vehicle Details') ?></a></div>
        </div>
    </section>
<?php } ?>

<div id="vehicle-popup-modal" style="display : none;" >
    <?php $make=$order->getMake(); 
    $model=$order->getModel(); 
    $year=$order->getYear(); 
    $plate=$order->getPlate(); 

    ?>   
    <form class="form" action="<?php echo $this->getUrl('shippingform/order/updatevehicle') ?>" id="mailsendform" method="post" >
        <input name="form_key" type="hidden" value="<?php /* @escapeNotVerified */ echo $block->getFormKey() ?>" />
        <input name="order_id" type="hidden" value="<?php echo $order->getId() ?>">
        <fieldset class="fieldset">
            
            <div class="admin__field field required">
                <label><?php echo __('Plate number') ?></label>
                <input type="text" class="input-text required-entry" data-validate="{required:true}" id="plate_number" <?php if (isset($plate)) { ?> value="<?php echo $plate; ?>" <?php } ?> name="plate_number" />
            </div>
            <?php //print_r($helper->getCheckoutVehcilelist()); ?>
            <div class="admin__field field required">
                <label><?php echo _('Make1 : ') ?></label>
                <select name="vehiclelist1" class="required-entry">
                    
                <?php foreach ($coreHelper->getOnestepCheckoutVehcilelist() as $vehcilelist) { ?>
                    <option value="<?php echo $vehcilelist['value']; ?>" <?php if ($make == $vehcilelist['value']) { ?> selected="selected" <?php } ?> ><?php echo $vehcilelist['label']; ?></option>
                <?php } ?>
                </select>
            </div>
            <div class="admin__field field required">
                <label><?php echo _('Model : ') ?></label>
                <select name="vehiclemodel1" class="required-entry">
                </select>
            </div>
            <div class="admin__field field required">
                <label><?php echo _('Year : ') ?></label>
                <select name="vehicleyear1" class="required-entry">
                </select>
            </div>
        </fieldset>
    </br>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" class="action submit primary" title="<?php  echo __('Submit') ?>">
                    <span><?php echo __('Submit') ?></span>
                </button>
            </div>
        </div>
    </form>
</div>

<?php $poData = $objectManager->create('\Hdweb\Purchaseorder\Model\Purchaseorder')->getCollection()->addfieldtofilter('orderreference_no',$order->getIncrementId());
    if (count($poData) > 0) {
        $grandSum = 0; 
        $totalMargin = 0; 
        ?>
        <section class="admin__page-section order-po">
                <div class="admin__page-section-title">
                    <span class="title"><?php echo $block->escapeHtml(__('Purchase Order Information')) ?></span>
                </div>
                <div>
                    <div class="field">
                        <span class="lable_field"><?php echo $block->escapeHtml(__('PO Number')) ?> </span>
                        <?php foreach ($poData as $po) { 
                            $grandSum = $grandSum+(double)$po->getGrandtotal();
                        ?>
                            <span class="text_field"><a target="_blank" href="<?php echo $this->getUrl('purchaseorder/create/edit').'po_id/'.$po->getId() ?>"><?php echo $po->getPoreferenceNo() ?></a></span> 
                        <?php } 
                        $totalMargin = number_format(((($order->getGrandtotal()-$grandSum)/$order->getGrandtotal())*100),2); ?>
                    </div>
                </div>
                <div>
                    <div class="field">
                        <span class="lable_field"><?php echo $block->escapeHtml(__('No. of POs') ) ?> </span><span class="text_field"><?php echo count($poData) ?></span> 
                    </div>
                    <div class="field">
                        <span class="lable_field"><?php echo $block->escapeHtml(__('PO Grand Total') )?> </span><span class="text_field"><?php echo $grandSum ?></span> 
                    </div>
                    <div class="field">
                        <span class="lable_field"><?php echo $block->escapeHtml(__('Total Margin'))?> </span><span class="text_field"><?php echo $totalMargin.'%' ?></span> 
                    </div>
                </div>
         </section>
<?php } ?>


<?php  /* Notify installer Popup  */  ?>

<div id="notify-installer-popup-modal" style="display : none;" >
    <form class="form" action="<?php echo $this->getUrl('installer/order/sendemailtoinstaller') ?>" id="mailsendform" method="post" >
        <input name="form_key" type="hidden" value="<?php /* @escapeNotVerified */ echo $block->getFormKey() ?>" />
        <input name="send_email" class="" ss="send_mail" id="send_mail" type="hidden" />
        <input name="order_id" type="hidden" value="<?php echo $order->getId() ?>">
        <fieldset class="fieldset">
            <div class="field required">
                <input type="hidden"   name="id" value="<?php  echo $order->getId() ?>" />
                <label><?php echo __('Appointment Date') ?></label>
                <input type="text" class="input-text required-entry hasDatepicker" data-validate="{required:true}" id="notify_installer_date" name="installer_date"  required />
                
            </div>
            </br>
             <div class="field required">
                <div>
                    <label class="admin__field-label"><?php echo __('Admin Comment') ?></label>
                </div>
                <div>
                    <textarea name="installer_comment" rows="5" cols="100"></textarea>
                </div>
            </div> 
        </fieldset>
    </br>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" class="action submit primary" title="<?php  echo __('Send Mail') ?>">
                    <span><?php echo __('Send Mail') ?></span>
                </button>
            </div>
        </div>
    </form>
</div>

<div id="notify-customer-popup-modal" style="display : none;" >
    <form class="form" action="<?php echo $this->getUrl('installer/order/sendemailtocustomer') ?>" id="customernotify" method="post" >
        <input name="form_key" type="hidden" value="<?php /* @escapeNotVerified */ echo $block->getFormKey() ?>" />
        <input name="send_email" class="customer_notify_send_mail" id="customer_notify_send_mail" type="hidden" />
        <input name="order_id" type="hidden" value="<?php echo $order->getId() ?>">
        <fieldset class="fieldset">
            <div class="field required">
                <input type="hidden"   name="id" value="<?php  echo $order->getId() ?>" />
                <label><?php echo __('Appointment Date') ?></label>
                <input type="text" class="input-text required-entry hasDatepicker" data-validate="{required:true}" id="customer_installer_date" name="installer_date" required />
                
            </div>
            </br>
             <div class="field required">
                <div>
                    <label class="admin__field-label"><?php echo __('Admin Comment') ?></label>
                </div>
                <div>
                    <textarea name="installer_comment" rows="5" cols="100"></textarea>
                </div>
            </div> 
        </fieldset>
    </br>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" class="action submit primary" title="<?php  echo __('Send Mail') ?>">
                    <span><?php echo __('Send Mail') ?></span>
                </button>
            </div>
        </div>
    </form>
</div>


<div id="installer-popup-modal" style="display : none;" >
    <?php 
    $allStores = $objectManager->create('Ecomteck\StoreLocator\Block\StoreLocator')->getStorePickupList();
    $allStores->setOrder('name', 'ASC');
    ?>
    <form class="form" action="<?php echo $this->getUrl('installer/order/updateinstaller') ?>" id="editintaller" method="post" >
        <input name="form_key" type="hidden" value="<?php /* @escapeNotVerified */ echo $block->getFormKey() ?>" />
        <input name="order_id" type="hidden" value="<?php echo $order->getId() ?>">
        <fieldset class="fieldset">
            <div class="field required">
                <label><?php echo __('Instller List') ?></label>
                <select name="installer">
                <?php foreach ($allStores as $store) { ?>
                    <option value="<?php echo $store->getStoresId(); ?>"><?php echo $store->getName().'('.$store->getAddress().')'; ?></option>
                <?php } ?>
                </select>
            </div>
        </fieldset>
    </br>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" class="action submit primary" title="<?php  echo __('Submit') ?>">
                    <span><?php echo __('Submit') ?></span>
                </button>
            </div>
        </div>
    </form>
</div>
<div id="assign_sales_person-modal" style="display : none;" >
    <form class="form" action="<?php echo $this->getUrl('salesperson/order/assignsalesperson') ?>" id="assignsalespersonendform" method="post" >
        <input name="form_key" type="hidden" value="<?php /* @escapeNotVerified */ echo $block->getFormKey() ?>" />
        <input name="order_id" type="hidden" value="<?php echo $order->getId() ?>">
        <fieldset class="fieldset">
            <div class="field required">
                <label><?php echo _('Salesperson List : ') ?></label>
                <select name="salesid" class="required-entry">
                    
                <?php foreach ($helper->getManagerList() as $key => $value) { ?>
                    <option value="<?php echo $key; ?>"><?php echo $value; ?></option>
                <?php } ?>
                </select>
            </div>
            <!-- <div class="field required">
                <div>
                    <label class="admin__field-label">Comments</label>
                </div>
                <div>
                    <textarea name="comment" class="required-entry" rows="5" cols="100"></textarea>
                </div>
            </div>  -->
        </fieldset>
    </br>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" class="action submit primary" title="<?php  echo __('Assign Salesperson') ?>">
                    <?php  if($order->getSalesPersonId()){ ?>
                       <span><?php echo __('Update Salesperson') ?></span>
                    <?php  } else { ?>
                             <span><?php echo __('Assign Salesperson') ?></span>
                    <?php  } ?>

                </button>
            </div>
        </div>
    </form>
</div>

<script>
    require(['jquery','Magento_Ui/js/modal/modal','mage/mage','mage/calendar'],
        function($,modal) 
        {   
            $('#notify_installer_date').datetimepicker({
                dateFormat: 'd/m/yy',
                timeFormat: 'HH:mm:ss',
                changeMonth: true,
                changeYear: true,
                showsTime: true
            });

            $('#customer_installer_date').datetimepicker({
                dateFormat: 'd/m/yy',
                timeFormat: 'HH:mm:ss',
                changeMonth: true,
                changeYear: true,
                showsTime: true
            });   
            
            $('.installer-button').click(function(event){
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'Notify Installer',
                buttons: []
            };
            
            var popup = modal(options, $('#notify-installer-popup-modal'));
            var email = '<?php echo isset($customerEmail) ? $customerEmail  : '' ?>';
            $(".send_mail").val(email);
            $('#notify-installer-popup-modal').modal('openModal');
          });

          $('.notify-customer-button').click(function(event){
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'Notify Customer',
                buttons: []
            };
            
            var customer_notify_popup = modal(options, $('#notify-customer-popup-modal'));
            var email = '<?php echo isset($customerEmail) ? $customerEmail  : '' ?>';
            $(".customer_notify_send_mail").val(email);
            $('#notify-customer-popup-modal').modal('openModal');
          });  

          $('.edit-installer-button').click(function(event){
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'Edit Installer',
                buttons: []
            };

            var popup = modal(options, $('#installer-popup-modal'));
            $('#installer-popup-modal').modal('openModal');
        });

        /* vehicle information */
            $('#vehicleData').click(function(event){
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'Vehicle Details',
                buttons: []
            };

            var popup = modal(options, $('#vehicle-popup-modal'));
            $('#vehicle-popup-modal').modal('openModal');
                $(document).ready(function(){
                    if ($("select[name='vehiclelist1']").has('option').length > 0) {    
                        var selectedVehicle = $("select[name='vehiclelist1']").children("option:selected").val();
                        $("select[name='vehiclelist1']").val(selectedVehicle).trigger('change');
                    }
                });
            }); 

            $(document).on('change', "select[name='vehiclelist1']", function() {
                var selectedmodel = $("select[name='vehiclelist1']").val();
                if (selectedmodel) {
                    getvehiclemodelAction(selectedmodel);
                }
            });

            $(document).on('change', "select[name='vehiclemodel1']", function() {
              var selectevehicledmodel = $("select[name='vehiclelist1']").val();
                     var selectedyear = $("select[name='vehiclemodel1']").val();
                     var data = {'make': selectevehicledmodel, 'model': selectedyear};
                     if (data) {
                        getvehicleyearAction(data);
                    }
            });

            function getvehiclemodelAction(area, responce) {
                $('body').trigger('processStart');

                return $.ajax({
                    url: '/shippingform/ajax/getvehiclemodel',
                    method: 'post',
                    data: JSON.stringify(area),
                    contentType: 'application/json; charset=UTF-8',
                    showLoader: true,
                    beforeSend: function(xhr){
                        //Empty to remove magento's default handler
                    }
                }).done(function (response) {
                    if (response) {
                        $.each(response, function (i, v) {         
                                $("select[name='vehiclemodel1']").html(v.vehiclemodel);
                                $("select[name='vehicleyear1']").html(v.vehicleyear);
                        });
                        var vehicleData = '<?php echo $order->getVehicleDetails(); ?>';
                        if (vehicleData.length > 0) {
                            var chechMake = "<?php echo unserialize($order->getVehicleDetails())['vechicle_data']['Make'] ?>"
                            if (chechMake == $("select[name='vehiclelist1']").val()) {
                                var modelSelected = "<?php echo unserialize($order->getVehicleDetails())['vechicle_data']['Model'] ?>";
                                $("select[name='vehiclemodel1']").val(modelSelected).trigger('change');
                            }
                        }
                    }
                    $('body').trigger('processStop');
                }).fail(function (response) {
                    //handle failure scenario
                });
            }

            function getvehicleyearAction(area, responce) {
                $('body').trigger('processStart');

                return $.ajax({
                    url: '/shippingform/ajax/getvehicleyear',
                    method: 'post',
                    data: JSON.stringify(area),
                    contentType: 'application/json; charset=UTF-8',
                    showLoader: true,
                    beforeSend: function(xhr){
                        //Empty to remove magento's default handler
                    }
                }).done(function (response) {
                    if (response) {
                        $.each(response, function (i, v) {         
                                $("select[name='vehicleyear1']").html(v.vehicleyear);
                        });
                        var vehicleData = '<?php echo $order->getVehicleDetails(); ?>';
                        if (vehicleData.length > 0) {
                            var chechMake = "<?php echo unserialize($order->getVehicleDetails())['vechicle_data']['Make'] ?>"
                            var chechModel = "<?php echo unserialize($order->getVehicleDetails())['vechicle_data']['Model'] ?>"
                            if (chechMake == $("select[name='vehiclelist1']").val() && chechModel == $("select[name='vehiclemodel1']").val()) {
                                var yearSelected = "<?php echo unserialize($order->getVehicleDetails())['vechicle_data']['Year'] ?>";
                                $("select[name='vehicleyear1']").val(yearSelected).trigger('change');
                            }
                        }
                    }
                    $('body').trigger('processStop');
                }).fail(function (response) {
                    //handle failure scenario
                });
            }
            
        /* vehicle information end */    

   });                 
</script>
<script>
    require(['jquery','Magento_Ui/js/modal/modal'],
        function($,modal) 
        {
            $('.assign_sales_person').click(function(event){
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'Select SalesPerson',
                buttons: []
            };

            var assign_sales_person_popup = modal(options, $('#assign_sales_person-modal'));

            $('#assign_sales_person-modal').modal('openModal');
        });
    });
</script>