<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Checkout\Block\Registration */
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
?>
<div id="registration" data-bind="scope:'registration'">
    <br />
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#registration": {
                "Magento_Ui/js/core/app": {
                   "components": {
                        "registration": {
                            "component": "Magento_Checkout/js/view/registration",
                            "config": {
                                "registrationUrl":
                                    "<?= $block->escapeJs($block->escapeUrl($block->getCreateAccountUrl())) ?>",
                                "email": "<?= $block->escapeJs($block->getEmailAddress()) ?>"
                            },
                            "children": {
                                "errors": {
                                    "component": "Magento_Ui/js/view/messages",
                                    "sortOrder": 0,
                                    "displayArea": "messages",
                                    "config": {
                                        "autoHideTimeOut": -1
                                     }
                                }
                            }
                        }
                    }
                }
            }
        }
    </script>
</div>
<?php if(!$customerSession->isLoggedIn()): ?>
<div class="container">
    <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('checkout_success_bottom')->toHtml(); ?>
</div>
<?php endif; ?>