<?php
/*
 * @category    Spotii
 * @package     Spotii_Spotiipay
 * @copyright   Copyright (c) Spotii (https://www.spotii.me/)
 */
?>

<?php if (!$block->getData('original_msg') && $block->getData('support_url')) : ?>
    <?= $block->escapeHtml(__(
        'Capture time for this order has been expired. Contact <a href="%1">Spotii Merchant Support</a>.',
        $block->getData('support_url')
    ), ['a']); ?>

<?php else: ?>
    <?= $block->escapeHtml(__(
        $block->getData('original_msg')
    )); ?>
<?php endif; ?>
