<?php
use Mirasvit\Core\Service\CspService;

/** @var \Mirasvit\Core\Block\Adminhtml\Manual $block */

$nonce = CspService::getNonce();

?>
<div class="mst-core__manual">
    <a href="<?= $block->escapeUrl($block->getManualUrl()) ?>"
       id="m__manual_link"
       title="<?= $block->escapeHtmlAttr($block->getTitle()) ?>"
       onclick="this.target='_blank'"><?= $block->escapeHtml($block->getTitle()) ?>
    </a>
</div>
<?php if ($block->getPosition() == 'bottom'): ?>
    <script<?php if ($nonce): ?> nonce="<?= $block->escapeHtml($nonce) ?>"<?php endif; ?> type="text/javascript">
        var helpLink = document.getElementById("m__manual_link");
        var width = helpLink.clientWidth;
        var margin = -width / 2;
        helpLink.style.marginLeft = margin + "px";
    </script>
<?php endif; ?>

