<div id="pickup-info-wrapper">
    <?php if($block->getPickupStore()): ?>
        <strong><?php echo __('Fitment Installer') ?>: </strong>
        <span class="price">
            <?php echo $this->helper('Ecomteck\StorePickup\Helper\Data')->getStoreNameById(
            $block->getPickupStore()); ?>
        </span>
    <?php endif; ?>
    <br/>
    <strong style="display: none;"><?php echo __('Pickup Date') ?>:</strong>
    <span class="price" style="display: none;"><?php echo $block->getPickupDate() ?></span>
    <br/>
    <strong style="display: none;"><?php echo __('Pickup Time') ?>:</strong>
    <span class="price" style="display: none;"><?php echo $block->getPickupTime() ?></span>
</div>
<script type="text/javascript">
    require(
        ['jquery'],
        function($) {
        	$('#pickup-info-wrapper').appendTo('.order-shipping-method div:last-child');
        }
    );
</script>