<?php
/**
 * @category   Hdweb
 * @package    Hdweb_Insurance
 * @author     vicky.hdit@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Hdweb\Insurance\Model\ResourceModel\Insurance;
 
class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection
{
    protected $_idFieldName = 'insurance_id';
    /**
     * Define model & resource model
     */
    protected function _construct()
    {
        $this->_init(
            'Hdweb\Insurance\Model\Insurance',
            'Hdweb\Insurance\Model\ResourceModel\Insurance'
        );
    }
}