<?php
$helper = $this->helper('MGS\Blog\Helper\Data');
$post = $block->getCurrentPost();
$showImage = $this->getConfig('general_settings/show_image');
$showAction = $this->getConfig('general_settings/show_action');
$sideBarBlock = $block->getLayout()->createBlock('MGS\Blog\Block\Sidebar');
?>
<div class="post-info-wrap">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-8">
                <div class="blog-post post-item-info">
                    <?php if ($showImage): ?>
                    <div class="post-image">
                        <?php echo $helper->getImagePost($post); ?>
                    </div>
                    <?php endif; ?>
                    <div class="post-info">
                        <div class="post-create-time">
                            <i class="fa fa-calendar"></i>
                            <?php echo __('%1', $block->formatDate($post->getCreatedAt(), \IntlDateFormatter::MEDIUM, false)); ?>
                        </div>
                        <?php /* <div class="published-by">
                <i class="fa fa-user"></i>
                <?php echo __('By ')?>
                        <span class="text-capitalize">
                            <?php if ($post->getUpdatedByUser()): ?>
                            <?php echo __('%1', $post->getUpdatedByUser()); ?>
                            <?php else: ?>
                            <?php echo __('%1', $post->getUser()); ?>
                            <?php endif; ?>
                        </span>
                    </div> */ ?>
                    <?php if ($post->getTags()): ?>
                    <?php $tags = explode(',', $post->getTags()); ?>
                    <div class="post-tags">
                        <i class="fa fa-tags"></i>
                        <?php foreach ($tags as $tag): ?>
                        <a title="<?php echo trim($tag); ?>"
                            href="<?php echo $helper->getTagUrl(trim($tag)); ?>"><?php echo trim($tag); ?></a>
                        <?php endforeach; ?>
                    </div>
                    <?php endif; ?>
                    <?php if ($this->getConfig('comment_settings/enabled')): ?>
                    <div class="comment-link">
                        <i class="fa fa-comment"></i>
                        <span>
                            <?php echo __('%1 comment(s)', $post->getCommentCount()) ?>
                        </span>
                    </div>
                    <?php endif; ?>
                </div>
                <?php if ($post->getContent()): ?>
                <div class="post-content">
                    <div class="post-short-description">
                        <?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance(); ?>
                        <?php echo $objectManager->get('\Magento\Cms\Model\Template\FilterProvider')->getBlockFilter()->filter($post->getContent()); ?>
                    </div>
                </div>
                <?php endif; ?>
                <?php if($helper->getStoreConfig('mpanel/share_config/enabel_share') && $helper->getStoreConfig('mpanel/share_config/share_blog_detail')): ?>
                <div class="text-right margin-top25">
                    <?php echo $block->getChildHtml('blog.detail.sharethis'); ?>
                </div>
                <?php endif ?>
                <?php if($showAction): ?>
                <div class="post-actions">
                    <?php $prevPost = $this->getPrevPost($post->getId()); ?>
                    <?php if($post->getId() != $prevPost['id']): ?>
                    <div class="prev-action action"><a
                            href="<?php echo $prevPost['url']; ?>"><?php echo __('Previous'); ?></a></div>
                    <?php endif ?>
                    <?php $nextPost = $this->getNextPost($post->getId()); ?>
                    <?php if($post->getId() != $nextPost['id']): ?>
                    <div class="next-action action"><a
                            href="<?php echo $nextPost['url']; ?>"><?php echo __('Next'); ?></a></div>
                    <?php endif ?>
                </div>
                <?php endif ?>
                <?php echo $block->getChildHtml('post_view_comment'); ?>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4">
            <div class="blog-sidebar">
                <?php if ($sideBarBlock->getConfig('sidebar_settings/show_categories')): ?>
                <?php $categories = $sideBarBlock->getCategories(); ?>
                <div class="widget">
                    <div class="widget-title">
                        <h3><?php echo __('Categories'); ?></h3>
                    </div>
                    <div class="widget-body">
                        <div class="categories">
                            <ul class="list-none">
                                <?php foreach ($categories as $category): ?>
                                <li><a href="<?php echo $category->getCategoryUrl(); ?>"
                                        title="<?php echo $category->getTitle(); ?>"><?php echo $category->getTitle(); ?></a>
                                </li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                    </div>
                </div>
                <?php endif; ?>
                <?php if ($sideBarBlock->getConfig('sidebar_settings/show_recent_posts')): ?>
                <?php $recentPostCollection = $sideBarBlock->getCollection(); ?>
                <div class="widget">
                    <div class="widget-title">
                        <h3><?php echo __('Recent Posts'); ?></h3>
                    </div>
                    <div class="widget-body">
                        <div class="resent-post">
                            <?php foreach ($recentPostCollection as $recentPost): ?>
                            <?php 
                                        // print_r($recentPost);
                                        // die();
                                        ?>
                            <div class="article d-flex align-items-center">

                                <div class="post-image picture">

                                        <img class="lazy img-responsive" src="<?php echo $recentPost->getImageUrl(); ?>"
                                             width="1" height="1"
                                            alt="<?php echo $recentPost->getTitle(); ?>">

                                </div>

                                <div class="article-content">
                                    <span><?php echo __('%1', $block->formatDate($recentPost->getPublishedAt(), \IntlDateFormatter::LONG, false)); ?></span>
                                    <a href="<?php echo $recentPost->getPostUrlWithNoCategory(); ?>"
                                        title="<?php echo $recentPost->getTitle(); ?>"><strong
                                            class=""><?php echo $recentPost->getTitle(); ?></strong></a>
                                </div>
                            </div>
                            <?php endforeach; ?>
                        </div>
                    </div>
                </div>
                <?php endif; ?>
                <?php if ($post->getTags()): ?>
                <?php $tags = explode(',', $post->getTags()); ?>
                <div class="widget">
                    <div class="widget-title">
                        <h3>Popular Tags</h3>
                    </div>
                    <div class="widget-body">
                        <div class="tags">
                            <ul class="list-none d-flex flex-wrap align-items-center">
                                <?php foreach ($tags as $tag): ?>
                                <li><a href="<?php echo $helper->getTagUrl(trim($tag)); ?>"
                                        title="<?php echo trim($tag); ?>"><?php echo trim($tag); ?></a></li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                    </div>
                </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
</div>
<style>
table,
th,
td {
    border: 1px solid black;
    margin: auto;
    text-align: center;
}
</style>


