<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$mediaUrl =$storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$brandPatternList = $block->getPatternbyBrand();
$brandDetail = $block->getBrand();
?>
<?php foreach($brandPatternList as $brandPatternListData):?>
	<div class="col-sm-4 col-lg-2 col-md-3 col-xs-6 col-12">
	   <div class="tyre_info_box_new">
		<?php if ($image = $block->getBrandImage()):?>
			<img src="<?php echo $block->getBrandImage();?>" alt="" class="new_tyre_logo" />
		<?php endif;?>
		  <h3><?php echo $brandPatternListData->getPattern();?></h3>
		  <div class="full_tyre_img">
			 <img src="<?php echo $mediaUrl.$brandPatternListData->getImage();?>" alt="" />
		  </div>
		  <div class="tyre_info_detail">
			<?php echo $brandPatternListData->getShortDescription();?>
			 <hr>
			 <a href="<?php echo $brandDetail->getUrlKey().'/'.$brandPatternListData->getUrlKey();?>" class="tyre_info_btn"><?php echo __('more details');?></a>  
		  </div>
	   </div>
	</div>
<?php endforeach;?>