<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var $block \Magento\Sales\Block\Order\Email\Items */
?>
<?php $_order = $block->getOrder() ?>
<?php 
if ($_order) { ?>
  <?php $_items = $_order->getAllItems(); 
  
  if($_order->getIsnotifyinstaller()){ //  For Notify Installer only ?>
    
     <table class="email-items" style="width: 100%">
        <thead>
            <tr style="background: #4bcf2e; color: white;">
                <th class="item-info" style="text-align: left;">
                    <?= $block->escapeHtml(__('ITEM')) ?>
                </th>
                <th class="item-qty" style="text-align: center;">
                    <?= $block->escapeHtml(__('QTY')) ?>
                </th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($_items as $_item) : ?>
            <tr>
                <td class="">
                    <p style="font-family: 'Arial', sans-serif;" class="product-name"><?= $block->escapeHtml($_item->getName()) ?></p>
                    <!-- <p style="font-family: 'Montserrat', sans-serif;" class="sku"><?= $block->escapeHtml(__('SKU')) ?>: <?= $block->escapeHtml($_item->getSku()) ?></p> -->
                </td>
                <td class="item-qty" style="text-align: center;"><?= (float) $_item->getQtyOrdered() ?></td>
            </tr>    
            <?php endforeach; ?>
        </tbody>
    </table> 

  <?php }else{ // For Customer Notify or Normal Order send ?>
    <table border="0" cellpadding="0" cellspacing="0" width="100%" style="padding:10px">
        <thead style="background-color:#2c2c34;color:white;font-family: 'Arial', sans-serif;">
            <tr style="height:40px;">
                <th scope="col" colspan="3" style="text-align:left;font-weight:100;font-size:14px;padding:3px 9px;font-family: 'Arial', sans-serif;">
                    <?= $block->escapeHtml(__('ITEM')) ?>
                </th>
                <th scope="col" style="text-align:center;font-weight:100;font-size:14px;padding:3px 9px;font-family: 'Arial', sans-serif;">
                    <?= $block->escapeHtml(__('PRICE')) ?>
                </th>
                <th scope="col" style="text-align:center;font-weight:100;font-size:14px;padding:3px 9px;font-family: 'Arial', sans-serif;">
                    <?= $block->escapeHtml(__('QTY')) ?>
                </th>
                <th scope="col" style="text-align:right;font-weight:100;font-size:14px;padding:3px 9px;font-family: 'Arial', sans-serif;">
                    <?= $block->escapeHtml(__('TOTAL')) ?>
                </th>
            </tr>
        </thead>
        <?php foreach ($_items as $_item) : ?>
            <?php if (!$_item->getParentItem()) : ?>
                <tbody>
                    <?= $block->getItemHtml($_item) ?>
                </tbody>
            <?php endif; ?>
        <?php endforeach; ?>
        <tfoot class="order-totals">
            <?= $block->getChildHtml('order_totals') ?>
        </tfoot>
    </table>

<?php } } ?>
