<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product view template
 *
 * @see \Magento\Catalog\Block\Product\View
 */
?>
<?php
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_themeHelper = $this->helper('MGS\Mpanel\Helper\Data');
$_product = $block->getProduct();
$_call = $block->getAtCall();
$_code = $block->getAtCode();
$_className = $block->getCssClass();
$_attributeType = $block->getAtType();
$_attributeAddAttribute = $block->getAddAttribute();
$_product = $_themeHelper->getModel('Magento\Catalog\Model\Product')->load($_product->getId());

if ($_attributeType == 'text') {
	$_attributeValue = ($_helper->productAttribute($_product, $_product->$_call(), $_code)) ? $_product->getAttributeText($_code) : '';
} elseif($_attributeType == 'list'){
	$_arrValue = $_product->getAttributeText($_code);
	$_attributeValue = implode(', ', (array)$_arrValue);
}else{
    $_attributeValue = $_product->getResource()->getAttribute($_code)->getFrontend()->getValue($_product);
}

?>
<?php
$listingHelper = $this->helper('Hdweb\Tyrefinder\Helper\Productlisting');
$brandName = $listingHelper->getAttributeValue($_product, 'mgs_brand');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
?>
<?php if ($_attributeValue && $_className != 'overview'): ?>
<?php if($brandName == 'Continental' && $_product->getAdditionalInfoDetail() != ''):?>
	<div class="product attribute <?php /* @escapeNotVerified */ echo $_className?>">
    <div class="value" <?php /* @escapeNotVerified */ echo $_attributeAddAttribute;?>><?php /* @escapeNotVerified */ echo $_attributeValue; ?></div>
	<div class="value additional-info-details" <?php /* @escapeNotVerified */ echo $_attributeAddAttribute;?>>
		<div class="additional_info_detail">
		<?php
		/* $patternId      = $_helper->productAttribute($_product, $_product->getPattern(), 'pattern');
		$brandId =	$_helper->productAttribute($_product, $_product->getMgsBrand(), 'mgs_brand');
		$productFactory = $objectManager->get('Magento\Catalog\Model\ResourceModel\Product\CollectionFactory');
		$collection = $productFactory->create();
		$collection->addAttributeToSelect('*');
		$collection->addAttributeToFilter('visibility', \Magento\Catalog\Model\Product\Visibility::VISIBILITY_BOTH);
		$collection->addAttributeToFilter('status',\Magento\Catalog\Model\Product\Attribute\Source\Status::STATUS_ENABLED);
		$collection->addAttributeToFilter('mgs_brand', $brandId);
		$collection->addAttributeToFilter('pattern', $patternId);

		if(count($collection->getData()) > 0){
			$rimArray = array();	
			foreach($collection as $rimProducts){
				$_rimproduct = $objectManager->get('Magento\Catalog\Model\Product')->load($rimProducts->getId());
				$rimSize     = $listingHelper->getAttributeValue($_rimproduct, 'rim');
				$rimArray[] = $rimSize;
			}
			$rim = array_unique($rimArray);
			asort($rim);?>
			<div class="dimensions additional-div">
			<h2>Dimensions</h2>
			<ul>
			<?php foreach($rim as $rimDimension):?>
				<li><?php echo $rimDimension;?></li>
			<?php endforeach;?>	
			</ul>
			</div>
		<?php } */ ?>	
			<?php echo $_product->getAdditionalInfoDetail();?>
		</div>
	</div>
</div>
<?php endif;?>
<?php elseif($_attributeValue && $_className == 'overview'): ?>
<div class="product attribute <?php /* @escapeNotVerified */ echo $_className?>">
    <div class="value std" <?php /* @escapeNotVerified */ echo $_attributeAddAttribute;?>><?php /* @escapeNotVerified */ echo $_attributeValue; ?></div>
</div>
<?php endif; ?>
