<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$currentProduct = $objectManager->get('Magento\Framework\Registry')->registry('current_product');//get current product
$partsCategory = $currentProduct->getResource()->getAttribute('parts_category')->getFrontend()->getValue($currentProduct);
if($partsCategory == 'Wheels'){
	echo $this->getLayout()->createBlock("Hdweb\Tyrefinder\Block\Finderpopup")->setTemplate("Hdweb_Tyrefinder::offset_tyre_finder_block.phtml")->toHtml();
}elseif($partsCategory == 'Motorcycle Tyres'){
	echo $this->getLayout()->createBlock("Hdweb\Tyrefinder\Block\Finderpopup")->setTemplate("Hdweb_Tyrefinder::motorcycle_tyre_finder_block.phtml")->toHtml();
}else{
	echo $this->getLayout()->createBlock("Hdweb\Tyrefinder\Block\Finderpopup")->setTemplate("Hdweb_Tyrefinder::tyre_finder_block.phtml")->toHtml();	
}

?>
<?php $crumbs = $block->getCrumbs(); ?>
<?php if ($crumbs && is_array($crumbs)) : ?>
<?php $mgsHelper = $this->helper('MGS\Mpanel\Helper\Data'); ?>
<div class="breadcrumbs 111">
    <div class="<?php if($mgsHelper->getStoreConfig('mpanel/breadcrumbs/fullwidth')): ?>container-fluid<?php else: ?>container<?php endif ?>">
		<ul class="items">
			<?php foreach ($crumbs as $crumbName => $crumbInfo) : ?>
				<li class="item <?= /* @escapeNotVerified */ $crumbName ?>">
				<?php if ($crumbInfo['link']) : ?>
					<a href="<?= /* @escapeNotVerified */ $crumbInfo['link'] ?>" title="<?= $block->escapeHtml($crumbInfo['title']) ?>"><?= $block->escapeHtml($crumbInfo['label']) ?></a>
				<?php else: ?>
					<?= $block->escapeHtml($crumbInfo['label']) ?>
				<?php endif; ?>
				</li>
			<?php endforeach; ?>
		</ul>
	</div>
</div>
<?php endif; ?>