<style type="text/css">
	body {
		color: #212121;
	}

	.img-responsive {
		display: block;
		height: 400px;
		width: auto !important;
		min-width: auto !important;
	}

	.value.std {
		color: #212121;
		font-weight: 800;
		font-size: 20px;
	}

	.product-info-main .product-info-price .price-box .price {
		font-weight: 900;
		color: #000;
	}

	.full-review.product-reviews-summary {
		display: none;
	}

	.margin-top65 {
		margin-top: 0 !important;
	}

	@media (max-width: 767px) {
		.img-responsive {
			margin: 0 auto;
		}
	}
</style>
<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product view template
 *
 * @see \Magento\Catalog\Block\Product\View\Description
 */
?>
<?php
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$listingHelper = $this->helper('Hdweb\Tyrefinder\Helper\Productlisting');
$_product = $block->getProduct();
$_call = $block->getAtCall();
$_code = $block->getAtCode();
$_className = $block->getCssClass();
$_attributeLabel = $block->getAtLabel();
$_attributeType = $block->getAtType();
$_attributeAddAttribute = $block->getAddAttribute();
$themeHelper = $this->helper('MGS\Mpanel\Helper\Data');

if ($_attributeLabel && $_attributeLabel == 'default') {
	$_attributeLabel = $_product->getResource()->getAttribute($_code)->getFrontendLabel();
}
if ($_attributeType && $_attributeType == 'text') {
	$_attributeValue = ($_helper->productAttribute($_product, $_product->$_call(), $_code)) ? $_product->getAttributeText($_code) : '';
} else {
	$_attributeValue = $_helper->productAttribute($_product, $_product->$_call(), $_code);
}
?>
<?php if ($_attributeValue) : ?>
	<?php if ($_className == 'overview') : ?>
		<div class="product attribute brand">
			<div class="value std">
				<?php //echo $listingHelper->getAttributeValue($_product, 'mgs_brand');
				?>
				<?php echo $this->getLayout()->createBlock("Mageplaza\Shopbybrand\Block\Product\Logo")->setTemplate("Mageplaza_Shopbybrand::product/logo.phtml")->toHtml(); ?>
			</div>
		</div>
		<?php if ($themeHelper->getStoreConfig('mpanel/product_details/short_description')) : ?>
			<div class="product attribute <?php /* @escapeNotVerified */ echo $_className ?>">
				<?php if ($_attributeLabel != 'none') : ?><strong class="type"><?php /* @escapeNotVerified */ echo $_attributeLabel ?></strong><?php endif; ?>
				<div class="value std" <?php /* @escapeNotVerified */ echo $_attributeAddAttribute; ?>><?php /* @escapeNotVerified */ echo $_attributeValue; ?></div>
			</div>
		<?php endif; ?>
	<?php elseif ($_className == 'sku') : ?>
		<?php if ($themeHelper->getStoreConfig('mpanel/product_details/sku')) : ?>
			<div class="product attribute <?php /* @escapeNotVerified */ echo $_className ?>">
				<?php if ($_attributeLabel != 'none') : ?><strong class="type"><?php /* @escapeNotVerified */ echo $_attributeLabel ?></strong><?php endif; ?>
				<span class="value" <?php /* @escapeNotVerified */ echo $_attributeAddAttribute; ?>><?php /* @escapeNotVerified */ echo $_attributeValue; ?></span>
			</div>
		<?php endif; ?>
		<?php /*<div class="product attribute">
				<span class="value"><?php echo $_product->getAdditionalInfo();?></span>
		</div> */ ?>
	<?php else : ?>
		<div class="product attribute <?php /* @escapeNotVerified */ echo $_className ?>">
			<?php if ($_attributeLabel != 'none' || $_attributeLabel != __('none')) : ?><strong class="type"><?php /* @escapeNotVerified */ echo $_attributeLabel ?></strong><?php endif; ?>
			<span class="value" <?php /* @escapeNotVerified */ echo $_attributeAddAttribute; ?>><?php /* @escapeNotVerified */ echo $_attributeValue; ?></span>
		</div>
	<?php endif ?>
<?php endif ?>