<link href="//db.onlinewebfonts.com/c/68590d1f06ad625cb73b5c34f85b4a1b?family=Luma-Icons" rel="stylesheet" type="text/css"/>
<style type="text/css">
.faq-collection {
  margin-bottom: 20px;
}
  .ui-accordion .ui-accordion-header {
    display: block;
    cursor: pointer;
    position: relative;
    margin: 10px 0 0 0;
    padding: 0.8em .5em 0.8em 1em;
    font-size: 15px;
    font-weight: bold;
  }
  .ui-accordion .ui-accordion-content {
    padding: 1em 2.2em;
    border-top: 0;
    overflow: auto;
  }

  .ui-slider.ui-state-disabled .ui-slider-handle,
  .ui-slider.ui-state-disabled .ui-slider-range {
    filter: inherit;
  }
  .ui-slider-vertical {
    width: .8em;
    height: 100px;
  }
  .ui-slider-vertical .ui-slider-handle {
    left: -.3em;
    margin-left: 0;
    margin-bottom: -.6em;
  }
  .ui-slider-vertical .ui-slider-range {
    left: 0;
    width: 100%;
  }
  .ui-slider-vertical .ui-slider-range-min {
    bottom: 0;
  }
  .ui-slider-vertical .ui-slider-range-max {
    top: 0;
  }

  .faq-accordion .ui-widget.ui-widget-content {
    border: 1px solid #c5c5c5;
  }
  .faq-accordion .ui-widget-content {
    border: 1px solid #dddddd;
    background: #ffffff;
    color: #333333;
  }
  .faq-accordion .ui-widget-content a {
    color: #333333;
  }

  .ui-state-default,
  .ui-widget-content .ui-state-default,
  .ui-widget-header .ui-state-default {
    border: 1px solid #c5c5c5;
    background: #f6f6f6;
    font-weight: normal;
    color: #454545;
  }

  .ui-state-hover a,
  .ui-state-hover a:hover,
  .ui-state-hover a:link,
  .ui-state-hover a:visited,
  .ui-state-focus a,
  .ui-state-focus a:hover,
  .ui-state-focus a:link,
  .ui-state-focus a:visited {
    color: #2b2b2b;
    text-decoration: none;
  }

  .ui-visual-focus {
    box-shadow: 0 0 3px 1px rgb(94, 158, 214);
  }
  .ui-state-active,
  .ui-widget-content .ui-state-active,
  .ui-widget-header .ui-state-active
  {
    border: 1px solid #4bcf2e;
    background: #4bcf2e;
    font-weight: normal;
    color: #ffffff;
  }

  .ui-state-active a,
  .ui-state-active a:link,
  .ui-state-active a:visited {
    color: #ffffff;
    text-decoration: none;
  }

  .group-title{
    margin: 25px 0;
    font-size: 18px;
    text-transform: uppercase;
    line-height: 1.5;
    padding-bottom: 0.25em;
    border-bottom: 1px solid #ddd;
    width: 100%;
    color: #4bcf2e;
    font-weight: bold;
  }

  .group-title i {
    float: left;
    width: 2.15em;
    border-bottom: 1px solid #b55;
    position: absolute;
    bottom: -1px;
    z-index: 9999;
    border-bottom-color: #4bcf2e;
  }

  .faq-groups {
    width: 100%;
    margin-bottom: 30px;
    text-align: center;
  }
  .faq-group {
    display: inline-block;
  }
  .faq-group-image {
    border: 1px solid #1979C3;
    padding: 20px;
    margin-right: 25px;
  }

  img.group-image {
    height: 100px;
    width: 100px;
  }

  .faq-groupname {
    font-size: 15px;
    font-weight: 700;
    text-align: center;
    text-transform: uppercase;
    margin: 10px 25px 0 0;
  }

  .faq-group a.group-link:hover {
    color: #ff5501;
    text-decoration: none;
  }

  .faq-group .faq-group-image:hover {
    border-color: #ff5501;
  }

  .faq-content .ui-accordion-header:hover {
    background-color: #4bcf2e;
    color: #ffffff;
  }

  .faq-group:hover{
    border-color: #ff5501;
  }

  .faq-collection {
    margin-bottom: 30px;
    float: left;
    width: 100%;
  }

  .ui-accordion .ui-state-default:after {
    content: '\f107';
    font-family: 'Line Awesome Free';
    float: right;
  }

  .ui-accordion .ui-accordion-header-active:after {
    content: '\f106';
    font-family: 'Line Awesome Free';
  }
    
</style>
<?php
/**
 * MagePrince
 * Copyright (C) 2020 Mageprince <info@mageprince.com>
 *
 * @package Mageprince_Faq
 * @copyright Copyright (c) 2020 Mageprince (http://www.mageprince.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author MagePrince <info@mageprince.com>
 */
?>
<?php
/** @var $block \Mageprince\Faq\Block\Index\Index */
$pageType = $block->getPageTypeAction();
$faqGroupCollection = $block->getFaqGroupCollection();
?>
<?php if ($block->isEnable()): ?>
    <?php if ($faqGroupCollection->getSize()): ?>
        <div class="faq-collection">
            <?php if ($block->getGroupId()): ?>
                <div id="faq-content" class="faq-content">
                    <?php if ($block->isShowGroupTitle()): ?>
                        <?php $groupData = $block->getGroupById($block->getGroupId()); ?>
                        <div class="group-title">
                            <?= /* @noEscape */ __($groupData->getGroupName()) ?>
                        </div>
                    <?php endif; ?>
                    <div class="faq-accordion">
                        <?php $faqCollection = $block->getFaqCollection($block->getGroupId()); ?>
                        <?php if ($faqCollection->getSize()): ?>
                            <?php foreach ($faqCollection as $faq): ?>
                                <h3><?= /* @noEscape */ __($faq->getTitle()) ?></h3>
                                <div>
                                    <p><?= /* @noEscape */  $block->filterOutputHtml($faq->getContent()); ?></p>
                                </div>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </div>
                </div>
            <?php else: ?>
                <?php if ($block->isShowGroup() || $pageType == 'ajax'): ?>
                    <div class="faq-groups">
                        <?php foreach ($faqGroupCollection as $group): ?>
                            <div class="faq-group">
                                <?php if ($block->isShowGroup() || $pageType == 'ajax'): ?>
                                    <div id="faq-group-image" class="faq-group-image">
                                        <a href="#group<?= /* @noEscape */  $group->getFaqgroupId(); ?>"
                                           class="group-link"
                                           groupId="<?= /* @noEscape */  $group->getFaqgroupId(); ?>">
                                            <?php if ($group->getIcon()): ?>
                                                <img class="group-image"
                                                     src="<?= /* @noEscape */  $block->getImageUrl($group->getIcon()); ?>" />
                                            <?php else: ?>
                                                <img class="group-image"
                                                     src="<?= /* @noEscape */  $block->getViewFileUrl('Mageprince_Faq::images/faq.png'); ?>" />
                                            <?php endif; ?>
                                        </a>
                                    </div>
                                <?php endif; ?>
                                <?php if ($block->isShowGroupTitle()): ?>
                                    <div class="faq-groupname">
                                        <a href="#group<?= /* @noEscape */  $group->getFaqgroupId(); ?>"
                                           class="group-link"
                                           groupId="<?= /* @noEscape */  $group->getFaqgroupId(); ?>">
                                            <?= /* @noEscape */  $group->getGroupName(); ?>
                                        </a>
                                    </div>
                                <?php endif; ?>
                            </div>
                        <?php endforeach; ?>
                    </div>
                <?php endif; ?>
                <div id="faq-content" class="faq-content">
                    <?php if ($pageType == 'scroll'): ?>
                        <?php foreach ($faqGroupCollection as $group): ?>
                            <div id="group<?= /* @noEscape */  $group->getFaqgroupId(); ?>">
                                <?php if ($block->isShowGroupTitle()): ?>
                                    <div class="group-title">
                                        <?= /* @noEscape */  $group->getGroupName(); ?>
                                    </div>
                                <?php endif; ?>
                                <div class="faq-accordion">
                                    <?php $faqCollection = $block->getFaqCollection($group->getId()); ?>
                                    <?php if ($faqCollection->getSize()): ?>
                                        <?php foreach ($faqCollection as $faq): ?>
                                            <h3><?= /* @noEscape */ __($faq->getTitle()) ?></h3>
                                            <div>
                                                <p>
                                                    <?= /* @noEscape */  $block->filterOutputHtml($faq->getContent()); ?>
                                                </p>
                                            </div>
                                        <?php endforeach; ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    <?php else:?>
                        <?php $group = $faqGroupCollection->getFirstItem(); ?>
                        <?php if ($block->isShowGroupTitle()): ?>
                            <div class="group-title" id="group<?= /* @noEscape */  $group->getFaqgroupId(); ?>">
                                <?= /* @noEscape */  $group->getGroupName(); ?>
                            </div>
                        <?php endif; ?>
                        <div class="faq-accordion">
                            <?php $faqCollection = $block->getFaqCollection($group->getId()); ?>
                            <?php if ($faqCollection->getSize()): ?>
                                <?php foreach ($faqCollection as $faq): ?>
                                    <h3><?= /* @noEscape */ __($faq->getTitle()) ?></h3>
                                    <div>
                                        <p><?= /* @noEscape */  $block->filterOutputHtml($faq->getContent()); ?></p>
                                    </div>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </div>
                    <?php endif; ?>
                </div>
            <?php endif; ?>
        </div>
    <?php else: ?>
        <div>
            <h1><?= /* @noEscape */ __('No FAQ Group available') ?></h1>
        </div>
    <?php endif; ?>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "*": {
            "faq": {
                "pageType" : "<?= /* @noEscape */ $pageType ?>",
                "ajax_url" : "<?= $block->escapeUrl($block->getBaseUrl()) ?>"
            }
        }
    }
</script>
