<?php
/**
 * @category   Hdweb
 * @package    Hdweb_Insurance
 * @author     vicky.hdit@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Hdweb\Insurance\Setup;

use Magento\Framework\Setup\InstallSchemaInterface;
use Magento\Framework\Setup\ModuleContextInterface;
use Magento\Framework\Setup\SchemaSetupInterface;

/**
 * @codeCoverageIgnore
 */
class InstallSchema implements InstallSchemaInterface
{
    /**
     * {@inheritdoc}
     * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
     */
    public function install(SchemaSetupInterface $setup, ModuleContextInterface $context)
    {
		$installer = $setup;
		$installer->startSetup();

		/**
		 * Creating table hdweb_insurance
		 */
		$table = $installer->getConnection()->newTable(
			$installer->getTable('hdweb_insurance')
		)->addColumn(
			'insurance_id',
			\Magento\Framework\DB\Ddl\Table::TYPE_INTEGER,
			null,
			['identity' => true, 'unsigned' => true, 'nullable' => false, 'primary' => true],
			'Insurance Id'
		)->addColumn(
			'make',
			\Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
			20,
			['nullable' => true],
			'Make'
		)->addColumn(
			'model',
			\Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
			20,
			['nullable' => true,'default' => null],
			'Model'
		)->addColumn(
			'policy_type',
			\Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
			20,
			['nullable' => true,'default' => null],
			'Policy Type'
		)->addColumn(
			'quote_id',
			\Magento\Framework\DB\Ddl\Table::TYPE_INTEGER,
			null,
			['nullable' => true,'default' => null],
			'Quote Id'
		)->addColumn(
			'company_name',
			\Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
			20,
			['nullable' => true,'default' => null],
			'Company Name'
		)->addColumn(
			'first_name',
			\Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
			20,
			['nullable' => true,'default' => null],
			'First Name'
		)->addColumn(
			'family_name',
			\Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
			20,
			['nullable' => true,'default' => null],
			'Family Name'
		)->addColumn(
			'phone',
			\Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
			20,
			['nullable' => true,'default' => null],
			'Phone'
		)->addColumn(
			'email',
			\Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
			20,
			['nullable' => true,'default' => null],
			'Phone'
		)->addColumn(
			'status',
			\Magento\Framework\DB\Ddl\Table::TYPE_INTEGER,
			1,
			['nullable' => false,'default' => 0],
			'Status'
		)/*->addColumn(
			'content',
			\Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
			'2M',
			['nullable' => true,'default' => null],
			'Content'
		)->addColumn(
			'image',
			\Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
			255,
			['nullable' => true,'default' => null],
			'Image'
		)*/->addColumn(
			'created_at',
			\Magento\Framework\DB\Ddl\Table::TYPE_TIMESTAMP,
			null,
			['nullable' => false],
			'Created At'
		)->addColumn(
			'updated_at',
			\Magento\Framework\DB\Ddl\Table::TYPE_TIMESTAMP,
			null,
			['nullable' => false],
			'Updated At'
		)->addColumn(
			'request_parameter_quote',
			\Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
			'2M',
			['nullable' => true,'default' => null],
			'Request Parameter Quote'
		)->addColumn(
			'response_parameter_quote',
			\Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
			'2M',
			['nullable' => true,'default' => null],
			'Response Parameter Quote'
		)->setComment(
            'Hdweb Insurance Table'
        );
		$installer->getConnection()->createTable($table);
		$installer->endSetup();
	}
}