<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php
/** @var \Magento\Catalog\Pricing\Render\FinalPriceBox $block */

/** ex: \Magento\Catalog\Pricing\Price\RegularPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */
$priceModel = $block->getPriceType('regular_price');

/** ex: \Magento\Catalog\Pricing\Price\FinalPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$_product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');
$listingHelper = $this->helper('Hdweb\Tyrefinder\Helper\Productlisting');
$isWholeSaleCustomer = $listingHelper->isWholeSaleCustomer();
$finalPrice = $listingHelper->getSet1OnlyPrice($_product);
$regularPrice = $listingHelper->getRegularOnlyPrice($_product);
$pricingHelper = $objectManager->get('Magento\Framework\Pricing\Helper\Data');
$finalPriceWithCurrency   = $pricingHelper->currency($finalPrice, true, false);
$regularPriceWithCurrency   = $pricingHelper->currency($finalPrice, true, false);
$storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
$currency = $storeManager->getStore()->getCurrentCurrencyCode();
?>
<?php if ($block->hasSpecialPrice()) :?>
    <span class="special-price">
        <span class="price-container price-final_price tax weee" itemprop="offers" itemscope="" itemtype="http://schema.org/Offer">
            <span class="price-label">Special Price</span>
            <span id="product-price-<?php echo $_product->getId(); ?>" data-price-amount="<?php echo $finalPrice; ?>" data-price-type="finalPrice" class="price-wrapper ">
                <span class="price"><?php echo $finalPriceWithCurrency; ?></span>
            </span>
            <meta itemprop="price" content="<?php echo $finalPrice; ?>">
            <meta itemprop="priceCurrency" content="<?php echo $currency; ?>">
        </span>
    </span>
    <span class="old-price">
        <span class="price-container price-final_price tax weee">
            <span class="price-label">Regular Price</span>
            <span id="old-price-<?php echo $_product->getId(); ?>" data-price-amount="<?php echo $regularPrice; ?>" data-price-type="oldPrice" class="price-wrapper ">
                <span class="price"><?php echo $regularPriceWithCurrency; ?></span>
            </span>
        </span>
    </span>
<?php else :?>
    <span class="price-container price-final_price tax weee" itemprop="offers" itemscope="" itemtype="http://schema.org/Offer">
        <span id="product-price-20066" data-price-amount="<?php echo $finalPrice; ?>" data-price-type="finalPrice" class="price-wrapper ">
            <span class="price"><?php echo $finalPriceWithCurrency; ?></span>
        </span>
        <meta itemprop="price" content="<?php echo $finalPrice; ?>">
        <meta itemprop="priceCurrency" content="<?php echo $currency; ?>">
    </span>
<?php endif; ?>

<?php if ($block->showMinimalPrice()) :?>
    <?php if ($block->getUseLinkForAsLowAs()) :?>
        <a href="<?= $block->escapeUrl($block->getSaleableItem()->getProductUrl()) ?>" class="minimal-price-link">
            <?= /* @noEscape */ $block->renderAmountMinimal() ?>
        </a>
    <?php else :?>
        <span class="minimal-price-link">
            <?= /* @noEscape */ $block->renderAmountMinimal() ?>
        </span>
    <?php endif?>
<?php endif; ?>
