<?php

/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<?php
$themeHelper = $this->helper('MGS\Mpanel\Helper\Data');
$canUsePanel = $themeHelper->acceptToUsePanel();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$store = $storeManager->getStore();
$mediaUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
?>
<div class="contact-form-content">

	<div class="car-logos">
		<ul>
			<li>
				<div class="box">
					<a href="/car-wheels.html?mgs_brand=7875"><img src="<?php echo $mediaUrl . 'car-wheels-and-rims/Vision.jpg'; ?>" alt="Vision Wheesl Online UAE"></a>
				</div>
			</li>
			<li>
				<div class="box">
					<a href="/car-wheels.html?mgs_brand=7815"><img src="<?php echo $mediaUrl . 'car-wheels-and-rims/fuel.jpg'; ?>" alt="Fuel Off-Road Wheels Online UAE"></a>
				</div>
			</li>
			<li>
				<div class="box">
					<a href="/car-wheels.html?mgs_brand=8464"><img src="<?php echo $mediaUrl . 'car-wheels-and-rims/blackrhino.jpg'; ?>" alt="Blackrhino Wheels Online UAE"></a>
				</div>
			</li>
			<li>
				<div class="box">
					<a href="/car-wheels.html?mgs_brand=8465"><img src="<?php echo $mediaUrl . 'car-wheels-and-rims/fpower.jpg'; ?>" alt="F-Power Wheels Online UAE"></a>
				</div>
			</li>
			<li>
				<div class="box">
					<a href="/car-wheels.html?mgs_brand=8470"><img src="<?php echo $mediaUrl . 'car-wheels-and-rims/niche.jpg'; ?>" alt="Niche Wheels Online UAE"></a>
				</div>
			</li>
			<li>
				<div class="box">
					<a href="/car-wheels.html?mgs_brand=8467"><img src="<?php echo $mediaUrl . 'car-wheels-and-rims/lenso.jpg'; ?>" alt="Lenso Wheels Online UAE"></a>
				</div>
			</li>
		</ul>
	</div>

	<div class="images-block margin-top30">
		<div class="image-wrap">
			<a href="/car-wheels.html"><img src="<?php echo $mediaUrl . 'custom-tire-with-logos.jpg'; ?>" alt="Custom Car Wheels and Rims Online at TyresVision"></a>
		</div>
	</div>

	<div class="text-block margin-top30">
		<h1>POPULAR WHEELS</h1>
		<p>Lets decorate your vehicle with custom set of luxury, racing, or off-road wheels.</p>
		<p>All our wheels are original with warranty. From chrome to black, from 18" to 26", we carry every aftermarket wheel.</p>
		<p>Take any vehicle or any brand and add wheels from some of the top brands in the newest styles and finishes and transform it into one sweet looking machine.</p>
	</div>

	<div class="brand-block margin-top30">
		<div class="top-logo">
			<img src="<?php echo $mediaUrl . 'car-wheels-and-rims/Toyota-Logo.png'; ?>" alt="Car Wheels and Rims for Toyota">
		</div>

		<div class="car-tyre">
			<a href="car-wheels.html">
				<div class="row">
					<div class="col-xs-12 col-sm-6">
						<div class="car">
							<img src="<?php echo $mediaUrl . 'car-wheels-and-rims/Toyota-Land-Cruiser.jpg'; ?>" alt="Toyota Land Cruiser Custom Car Wheels and Rims in UAE">
						</div>
					</div>
					<div class="col-xs-12 col-sm-6">
						<div class="car-tyre-inner">
							<img src="<?php echo $mediaUrl . 'car-wheels-and-rims/Vision-Rim.jpg'; ?>" alt="Vision Wheels for Land Cruiser in UAE">
						</div>
					</div>
				</div>
			</a>
		</div>

		<div class="car-tyre">
			<a href="car-wheels.html">
				<div class="row">
					<div class="col-xs-12 col-sm-6">
						<div class="car">
							<img src="<?php echo $mediaUrl . 'car-wheels-and-rims/Toyota-Camry.jpg'; ?>" alt="Toyota Camry Custom Car Wheels and Rims in UAE">
						</div>
					</div>
					<div class="col-xs-12 col-sm-6">
						<div class="car-tyre-inner">
							<img src="<?php echo $mediaUrl . 'car-wheels-and-rims/Vision-Rim-2.jpg'; ?>" alt="Vision Wheels for Camry in UAE">
						</div>
					</div>
				</div>
			</a>
		</div>
	</div>

	<div class="brand-block margin-top30">
		<div class="top-logo">
			<img src="<?php echo $mediaUrl . 'car-wheels-and-rims/Nissan-Logo.png'; ?>" alt="Nissan Car Wheels and Rims Online in UAE">
		</div>

		<div class="car-tyre">
			<a href="car-wheels.html">
				<div class="row">
					<div class="col-xs-12 col-sm-6">
						<div class="car">
							<img src="<?php echo $mediaUrl . 'car-wheels-and-rims/Nissan-Patrol.jpg'; ?>" alt="Nissan Patrol Car Wheels and Rims Online UAE">
						</div>
					</div>
					<div class="col-xs-12 col-sm-6">
						<div class="car-tyre-inner">
							<img src="<?php echo $mediaUrl . 'car-wheels-and-rims/Vision-Rim-3.jpg'; ?>" alt="Vision Wheels and Rims for Nissan Patrol">
						</div>
					</div>
				</div>
			</a>
		</div>
	</div>

	<div class="brand-block margin-top30">
		<div class="top-logo">
			<img src="<?php echo $mediaUrl . 'car-wheels-and-rims/Mitsubishi-Logo.png'; ?>" alt="Mitsubishi Car Wheels and Rims Online UAE">
		</div>

		<div class="car-tyre">
			<a href="car-wheels.html">
				<div class="row">
					<div class="col-xs-12 col-sm-6">
						<div class="car">
							<img src="<?php echo $mediaUrl . 'car-wheels-and-rims/Mitsubishi-Pajero.jpg'; ?>" alt="Mitsubishi Pajero Wheels Rims in UAE">
						</div>
					</div>
					<div class="col-xs-12 col-sm-6">
						<div class="car-tyre-inner">
							<img src="<?php echo $mediaUrl . 'car-wheels-and-rims/Vision-Rim.jpg'; ?>" alt="Vision Wheels and Rims for Mitsubishi Pajero">
						</div>
					</div>
				</div>
			</a>
		</div>
	</div>

	<div class="brand-block margin-top30">
		<div class="top-logo">
			<img src="<?php echo $mediaUrl . 'car-wheels-and-rims/Ford-Logo.png'; ?>" alt="Ford Car Wheels and Rims online UAE">
		</div>

		<div class="car-tyre">
			<a href="car-wheels.html">
				<div class="row">
					<div class="col-xs-12 col-sm-6">
						<div class="car">
							<img src="<?php echo $mediaUrl . 'car-wheels-and-rims/Ford-F-150.jpg'; ?>" alt="Ford F 150 Car Wheels and Rims Online">
						</div>
					</div>
					<div class="col-xs-12 col-sm-6">
						<div class="car-tyre-inner">
							<img src="<?php echo $mediaUrl . 'car-wheels-and-rims/Vision-Rim-4.jpg'; ?>" alt="Vision Car Rims for Ford F 150 in UAE">
						</div>
					</div>
				</div>
			</a>
		</div>
	</div>

	<div class="brand-block margin-top30">
		<div class="top-logo">
			<img src="<?php echo $mediaUrl . 'car-wheels-and-rims/Jeep-Logo.png'; ?>" alt="Jeep Wheels and Rims Online in UAE">
		</div>

		<div class="car-tyre">
			<a href="car-wheels.html">
				<div class="row">
					<div class="col-xs-12 col-sm-6">
						<div class="car">
							<img src="<?php echo $mediaUrl . 'car-wheels-and-rims/Jeep-Wrangler.jpg'; ?>" alt="Jeep Wrangler Online Rims and Wheels in UAE">
						</div>
					</div>
					<div class="col-xs-12 col-sm-6">
						<div class="car-tyre-inner">
							<img src="<?php echo $mediaUrl . 'car-wheels-and-rims/Red-Rim.jpg'; ?>" alt="Blackrhino Wheels and Rims Online for Jeep Wrangler">
						</div>
					</div>
				</div>
			</a>
		</div>
	</div>

	<div class="brand-block margin-top30">
		<div class="top-logo">
			<img src="<?php echo $mediaUrl . 'car-wheels-and-rims/Hummer-Logo.png'; ?>" alt="Hummer Rims and Wheels Online in UAE">
		</div>

		<div class="car-tyre">
			<a href="car-wheels.html">
				<div class="row">
					<div class="col-xs-12 col-sm-6">
						<div class="car">
							<img src="<?php echo $mediaUrl . 'car-wheels-and-rims/Hummer-H2.jpg'; ?>" alt="Hummer H2 Wheels and Rims in UAE">
						</div>
					</div>
					<div class="col-xs-12 col-sm-6">
						<div class="car-tyre-inner">
							<img src="<?php echo $mediaUrl . 'car-wheels-and-rims/Vision-Rim-2.jpg'; ?>" alt="Get Vision Wheels and Rims for Hummer">
						</div>
					</div>
				</div>
			</a>
		</div>
	</div>

	<div class="brand-block margin-top30">
		<div class="top-logo">
			<img src="<?php echo $mediaUrl . 'car-wheels-and-rims/BMW-Logo.png'; ?>" alt="BMW Rims and Wheels Online in UAE">
		</div>

		<div class="car-tyre">
			<a href="car-wheels.html">
				<div class="row">
					<div class="col-xs-12 col-sm-6">
						<div class="car">
							<img src="<?php echo $mediaUrl . 'car-wheels-and-rims/BMW-X5.jpg'; ?>" alt="BMW X5 Wheels and Rims online UAE">
						</div>
					</div>
					<div class="col-xs-12 col-sm-6">
						<div class="car-tyre-inner">
							<img src="<?php echo $mediaUrl . 'car-wheels-and-rims/Black-Red.jpg'; ?>" alt="Get Fuel Wheels and Rims for BMW in UAE">
						</div>
					</div>
				</div>
			</a>
		</div>
	</div>

	<div class="car-notes margin-top20">
		<span>Note: OEM is different from original, OEM means from car manufacturer, which we do not sell.</span>
	</div>

	<!--  <div class="images-block margin-top30">
 <div class="image-wrap">
      	<img src="<?php //echo $mediaUrl.'wysiwyg/car-wheels-logo.jpg';
					?>" alt="Buy Best Car Wheels and Rims in UAE online at TyresVision">
      </div>
</div> 
   -->
	<div class="content-block margin-top40 margin-bottom40">
		<h2>Buy top brands of Alloy Rims/wheels in the newest styles and transform your Car into one sweet looking machine.</h2>
		<h3>Take your wheels to the next level - Try it with your CAR!!</h3>
	</div>


	<div class="form-wrap">
		<div class="row">
			<div class="col-sm-12 col-xs-12">
				<h3 class="text-uppercase margin-bottom15"><?php echo __('SEND US A MESSAGE'); ?></h3>
				<form class="form contact" action="/contact/index/post/" id="contact-form" method="post" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>" data-mage-init='{"validation":{}}'>
					<div class="row">
						<div class="col-sm-6 col-xs-12">
							<div class="form-group name required">
								<label for="name"><?php echo __('Customer Name'); ?></label>
								<input name="name" id="name" title="<?php /* @escapeNotVerified */ echo __('Name') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text form-control" type="text" data-validate="{required:true}" />
							</div>
						</div>
						<div class="col-sm-6 col-xs-12">
							<div class="form-group email required">
								<label for="email"><?php echo __('Email'); ?></label>
								<input name="email" id="email" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text form-control" type="email" data-validate="{required:true, 'validate-email':true}" />
							</div>
						</div>
						<div class="col-sm-12 col-xs-12">
							<div class="form-group telephone required">
								<label for="telephone"><?php echo __('Customer Mobile Number'); ?></label>
								<input name="telephone" id="telephone" title="<?php /* @escapeNotVerified */ echo __('Customer Mobile Number') ?>" value="" class="input-text form-control" type="text" data-validate="{required:true}" />
							</div>
						</div>
						<div class="col-sm-12 col-xs-12">
							<div class="form-group make required">
								<label for="make"><?php echo __('Make'); ?></label>
								<input name="make" id="make" title="<?php /* @escapeNotVerified */ echo __('Make') ?>" value="" class="input-text form-control" type="text" data-validate="{required:true}" />
							</div>
						</div>
						<div class="col-sm-12 col-xs-12">
							<div class="form-group model required">
								<label for="model"><?php echo __('Model'); ?></label>
								<input name="model" id="model" title="<?php /* @escapeNotVerified */ echo __('Model') ?>" value="" class="input-text form-control" type="text" data-validate="{required:true}" />
							</div>
						</div>
						<div class="col-sm-12 col-xs-12">
							<div class="form-group year required">
								<label for="year"><?php echo __('Year'); ?></label>
								<input name="year" id="year" title="<?php /* @escapeNotVerified */ echo __('Year') ?>" value="" class="input-text form-control" type="text" data-validate="{required:true}" />
							</div>
						</div>
						<div class="col-sm-12 col-xs-12" style="display: none;">
							<div class="form-group comment required">
								<label for="comment"><?php echo __('Comment'); ?></label>
								<textarea name="comment" id="comment" title="<?php /* @escapeNotVerified */ echo __('What’s on your mind?') ?>" class="input-text form-control" rows="4" data-validate="{required:true}">Car wheels and rims inquiry</textarea>
							</div>
						</div>
					</div>
					<div class="actions-toolbar">
						<input type="hidden" name="hideit" id="hideit" value="" />
						<button type="submit" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>" class="action submit btn btn-primary">
							<span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
						</button>
					</div>
				</form>
			</div>
		</div>
	</div>

	<!-- <div class="images-block margin-top60">
 <div class="image-wrap">
      	<img src="<?php //echo $mediaUrl.'wysiwyg/car-wheels-tyre.jpg';
					?>" alt="">
      </div>
</div> -->


</div>