<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$store = $storeManager->getStore();
$mediaUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA); ?>




<section class="section three-column-images service-content">
   <div class="container p-0">
      <div class="text-block text-center">
         <h1>Car Services</h1>
      </div>
      <div class="row">
         <div class="col-lg-12 col-md-12 col-sm-12">
            <!-- <div class="content-image">
               <img src="<?php // echo $mediaUrl . 'images/oil-change-image.webp'; ?>" alt="Ford F 150 Car Wheels and Rims Online">
            </div> -->
            <div class="content-image">
               <img src="<?php echo $mediaUrl . 'images/oil-change-2.webp'; ?>" alt="Ford F 150 Car Wheels and Rims Online">
            </div>
         </div>
         <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="text-content">
               <div class="section-title">
                  <h2>Get a Quote  within 10 minutes</h2>
                  <h3>Discounted price from our partner Top Garages in Dubai and Abu Dhabi</h3>
               </div>
               <div class="text-wrap">
                  <p>Our partner team knows their stuff, and they’ll be able to perform a thorough service on your vehicle</p>
                  <p>Simply complete the form below and one of our service consultants will contact you shortly…</p>
               </div>
            </div>
         </div>
      </div>
   </div>
</section>
<section class="section three-column-images service-form">
   <div class="container p-0">
      <div class="row">
         <div class="col-lg-8 col-md-8 col-sm-12">
            <div class="service-form-content">
               <h3 class="text-uppercase margin-bottom15">Get Quotation</h3>
               <form class="form contact" action="/contact/index/post/" id="car-service-form" method="post" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>" data-mage-init='{"validation":{}}'>
                  <div class="row">
                     <div class="col-sm-6 col-xs-12">
                        <div class="form-group name required">
                           <label for="name">Name</label>
                           <input name="name" id="name" title="<?php /* @escapeNotVerified */ echo __('Name') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text form-control" type="text" data-validate="{required:true}"/>
                        </div>
                     </div>
                     <div class="col-sm-6 col-xs-12">
                        <div class="form-group telephone required">
                           <label for="telephone">Mobile Number</label>
                           <input name="telephone" id="telephone" title="<?php /* @escapeNotVerified */ echo __('Mobile Number') ?>" value="" class="input-text form-control" type="text" data-validate="{required:true}" />
                        </div>
                     </div>
                     <div class="col-sm-6 col-xs-12">
                        <div class="form-group model required">
                           <label for="model">Car Model</label>
                           <input id="model" class="input-text form-control" title="Vehicle Model" name="model" type="text" value="" data-validate="{required:true}" />
                        </div>
                     </div>
                     <div class="col-sm-6 col-xs-12">
                        <div class="form-group year required">
                           <label for="year">Car Year</label>
                           <input id="year" class="input-text form-control" title="Vehicle Year" name="year" type="text" value="" data-validate="{required:true}" /">
                        </div>
                     </div>
                     <div class="col-sm-12 col-xs-12">
                        <div class="form-group email required">
                           <label for="email">Email</label>
                           <input name="email" id="email" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text form-control" type="email" data-validate="{required:true, 'validate-email':true}"/>
                        </div>
                     </div>
                     <div class="col-sm-12 col-xs-12" style="display: none">
                        <div class="form-group email required">
                           <label for="comment">Comment</label>
                           <textarea name="comment" id="comment" title="<?php /* @escapeNotVerified */ echo __('What’s on your mind?') ?>" class="input-text form-control" rows="4" data-validate="{required:true}">N/A</textarea>
                        </div>
                     </div>
                  </div>
                  <div class="actions-toolbar">
                     <button class="action submit btn btn-primary" title="Submit" type="submit"> Submit </button>
                  </div>
               </form>
            </div>
         </div>
      </div>
   </div>
</section>


<style>
   h1.page-header {
    display: none;
}

.cms-car-services .page-title-wrapper {
    padding: 0;
}

.cms-car-services .text-block h1 {
    margin-bottom: 20px;
    font-size: 30px;
}

.cms-car-services .text-block h3 {
    margin-bottom: 15px;
}

.cms-car-services .text-block ul {
    margin: 0 0 0 16px;
}

.cms-car-services .text-block ul li {
    list-style-type: disc;
    margin-bottom: 8px;
}

.cms-car-services .text-block.text-center {
    text-align: center;
}

.cms-car-services .images-block .image-wrap img {
    max-width: 100%;
    border: 4px double #eee;
}

table {
    width: 100%;
}

table tr td {
    padding: 8px 5px;
}

table,
th,
td {
    border: 1px solid black;
}

td {
    text-align: center;
}

.form-wrap {
    max-width: 70%;
    margin-left: auto;
    margin-right: auto;
    background-color: #f6f6f6;
    padding: 40px;
}


.service-content {
    padding-top: 30px;
    padding-bottom: 50px;
}

.service-content .content-image {
    margin-top: 30px;
}

.service-content .content-image img {
    width: 100%;
}

.service-content .text-content .section-title {
    text-align: center;
    margin-top: 50px;
}


.service-content .text-content .section-title h2 {
    margin-bottom: 20px;
    font-size: 30px;
}

.service-content .text-content .text-wrap {
    margin-top: 30px;
    text-align: center;
}

.service-content .text-content .text-wrap p {
    font-style: italic;
}


.service-form .service-form-content {
    background-color: #f6f6f6;
    padding: 40px;
}

.service-form .container .row {
    justify-content: center;
}


@media screen and (max-width: 767px) {
    .form-wrap {
        max-width: 100%;
    }

    table tr td {
        padding: 4px 2px;
        font-size: 12px;
    }

    .p-0 {
        padding: 0;
    }

    .service-content {
        padding-top: 0;
    }

    .service-content .text-content .section-title h2,
    .cms-car-services .text-block h1 {
        font-size: 23px;
    }

    .service-content .content-image {
        margin-top: 15px;
    }


    .service-content .text-content .section-title h3 {
        font-size: 16px;
    }

    .service-content .text-content .text-wrap {
        margin-top: 20px;
    }

    .service-form .service-form-content {
        padding: 35px 15px;
    }


}
</style>