<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$store = $storeManager->getStore();
$mediaUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
?>
<div class="container p-0">
    <div class="text-block text-center">
      <h1>Car Services</h1>
      <p><strong>Save approximately 40% on service bills…</strong></p>
      <p>Enjoy peace of mind with <strong>TyresVision Gold Maintenance Package</strong></p>
    </div>
    <div class="margin-top30">
      <table width="800">
        <tbody>
          <tr>
            <td colspan="3">
              <p><strong>TyresVision Gold Package Prices</strong></p>
            </td>
          </tr>
          <tr>
            <td colspan="3">
              <p><strong>German Brands (BMW/Merc/VW/Audi/Porsche/Land Rover/Jaguar/Mini)</strong></p>
            </td>
          </tr>
          <tr>
            <td>
              <p><strong>Engine</strong></p>
            </td>
            <td>
              <p><strong>Max Discount</strong></p>
            </td>
            <td>
              <p>Retail price</p>
            </td>
          </tr>
          <tr>
            <td>
              <p><strong>4 cylinder</strong></p>
            </td>
            <td>
              <p>AED 3,240</p>
            </td>
            <td>
              <p>AED 3,600</p>
            </td>
          </tr>
          <tr>
            <td>
              <p><strong>6 cylinder</strong></p>
            </td>
            <td>
              <p>AED 3,780</p>
            </td>
            <td>
              <p>AED 4,200</p>
            </td>
          </tr>
          <tr>
            <td>
              <p><strong>8 cylinder</strong></p>
            </td>
            <td>
              <p>AED 4,770</p>
            </td>
            <td>
              <p>AED 5,300</p>
            </td>
          </tr>
          <tr>
            <td colspan="3">
              <p><strong>Japanese Brands (Toyota/Nissan/Honda/Mazda/Infiniti/Lexus/Suzuki)</strong></p>
            </td>
          </tr>
          <tr>
            <td>
              <p><strong>Engine</strong></p>
            </td>
            <td>
              <p><strong>Max Discount</strong></p>
            </td>
            <td>
              <p>Retail price</p>
            </td>
          </tr>
          <tr>
            <td>
              <p><strong>4 cylinder</strong></p>
            </td>
            <td>
              <p>AED 2,205</p>
            </td>
            <td>
              <p>AED 2,450</p>
            </td>
          </tr>
          <tr>
            <td>
              <p><strong>6 cylinder</strong></p>
            </td>
            <td>
              <p>AED 3,060</p>
            </td>
            <td>
              <p>AED 3,400</p>
            </td>
          </tr>
          <tr>
            <td>
              <p><strong>8 cylinder</strong></p>
            </td>
            <td>
              <p>AED 3,870</p>
            </td>
            <td>
              <p>AED 4,300</p>
            </td>
          </tr>
          <tr>
            <td colspan="3">
              <p><strong>American Brands (GMC/Chevy/Cadillac/Dodge/Jeep)</strong></p>
            </td>
          </tr>
          <tr>
            <td>
              <p><strong>Engine</strong></p>
            </td>
            <td>
              <p><strong>Max Discount</strong></p>
            </td>
            <td>
              <p>Retail price</p>
            </td>
          </tr>
          <tr>
            <td>
              <p><strong>4 cylinder</strong></p>
            </td>
            <td>
              <p>AED 2,340</p>
            </td>
            <td>
              <p>AED 2,600</p>
            </td>
          </tr>
          <tr>
            <td>
              <p><strong>6 cylinder</strong></p>
            </td>
            <td>
              <p>AED 3,420</p>
            </td>
            <td>
              <p>AED 3,800</p>
            </td>
          </tr>
          <tr>
            <td>
              <p><strong>8 cylinder</strong></p>
            </td>
            <td>
              <p>AED 3,870</p>
            </td>
            <td>
              <p>AED 4,300</p>
            </td>
          </tr>
          <tr>
            <td colspan="3">
              <p><strong>Korean Brands (KIA/Hyundai)</strong></p>
            </td>
          </tr>
          <tr>
            <td>
              <p><strong>Engine</strong></p>
            </td>
            <td>
              <p><strong>Max Discount</strong></p>
            </td>
            <td>
              <p>Retail price</p>
            </td>
          </tr>
          <tr>
            <td>
              <p><strong>4 cylinder</strong></p>
            </td>
            <td>
              <p>AED 2,250</p>
            </td>
            <td>
              <p>AED 2,500</p>
            </td>
          </tr>
          <tr>
            <td>
              <p><strong>6 cylinder</strong></p>
            </td>
            <td>
              <p>AED 3,150</p>
            </td>
            <td>
              <p>AED 3,500</p>
            </td>
          </tr>
          <tr>
            <td colspan="3">
              <p><strong><em>NOTE: Super Cars will be priced separately </em></strong></p>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="text-block margin-top30">
      <h3>Package Includes the below:</h3>
      <ul>
        <li>5 Fully Synthetic Oil Changes (5 X 10,000 Kms. Oil &amp; Filter Service).</li>
        <li>1 Engine Air Intake Filter.</li>
        <li>1 1 A/C Cabin Filter.</li>
        <li>1 A/C Freon Gas Recharge.</li>
        <li>1 Spark Plug (Set) Replacement (Up To 8 Spark Plugs).</li>
        <li>1 Brake Fluid Flush.</li>
        <li>1 Power Steering Fluid Flush.</li>
        <li>1 Coolant Flush.</li>
        <li>1 Differential Fluid Flush (If Applicable).</li>
        <li>1 Replacement Of Front Brake Pads Set (Sensor Included If Applicable).</li>
        <li>1 Replacement Of Rear Brake Pads Set (Sensor Included If Applicable).</li>
        <li>4 Discs Skimming (Once Per Corner).</li>
        <li>1 Time Interior Detailing.</li>
      </ul>
    </div>
    <div class="text-block margin-top30">
      <h3>PLUS + + FREE Services below:</h3>
      <ul>
        <li><strong><em><u>Free</u></em></strong><em> Exterior Car wash and Interior Vacuum.</em></li>
        <li><strong><em><u>Free</u></em></strong><em>24 Points Car inspection and Report.</em></li>
        <li><strong><em><u>Free</u></em></strong><em> Tyres Rotation.</em></li>
        <li><strong><em><u>Free</u></em></strong><em> Fluid Top Up.</em></li>
        <li><strong><em><u>Free</u></em></strong><em> Wheel Alignment Check.</em></li>
      </ul>
    </div>
    <div class="text-block margin-top30">
      <h3>Call or WhatsApp - 24/7</h3>
      <a class="btn btn-primary" href="tel:+971 800 847 466">800 VISION</a> <a class="btn btn-secondary" href="https://api.whatsapp.com/send?phone= +971800847466&amp;text=Hello%20TyresVision">800 847466</a>
    </div>
    <div class="images-block margin-top30">
      <div class="image-wrap">
        <!-- <img class="img-responsive" src="https://www.tyresvision.com/media/wysiwyg/mechanincal-work-2.jpg" alt="Car Services"> -->
        <img class="img-responsive" src="<?php echo $mediaUrl.'wysiwyg/mechanincal-work-2.jpg';?>" alt="Car Services">
        
      </div>
    </div>
    <div class="form-wrap margin-top30">
      <div class="row">
        <div class="col-sm-12 col-xs-12">
          <h3 class="text-uppercase margin-bottom15">SEND US A MESSAGE</h3>
          <form class="form contact" action="/contact/index/post/" id="contact-form" method="post" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>" data-mage-init='{"validation":{}}'>
          <div class="row">
            <div class="col-sm-6 col-xs-12">
              <div class="form-group name required">
                <label for="name">Name</label>
                <input name="name" id="name" title="<?php /* @escapeNotVerified */ echo __('Name') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text form-control" type="text" data-validate="{required:true}"/>
              </div>
            </div>
            <div class="col-sm-6 col-xs-12">
              <div class="form-group telephone required">
                <label for="telephone">Mobile Number</label>
                <input name="telephone" id="telephone" title="<?php /* @escapeNotVerified */ echo __('Mobile Number') ?>" value="" class="input-text form-control" type="text" data-validate="{required:true}" />
              </div>
            </div>
            <div class="col-sm-6 col-xs-12">
              <div class="form-group model required">
                <label for="model">Vehicle Model</label>
                <input id="model" class="input-text form-control" title="Vehicle Model" name="model" type="text" value="" data-validate="{required:true}" />
              </div>
            </div>
            <div class="col-sm-6 col-xs-12">
              <div class="form-group year required">
                <label for="year">Vehicle Year</label>
                <input id="year" class="input-text form-control" title="Vehicle Year" name="year" type="text" value="" data-validate="{required:true}" /">
              </div>
            </div>
            <div class="col-sm-12 col-xs-12">
              <div class="form-group email required">
                <label for="email">Email</label>
                <input name="email" id="email" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text form-control" type="email" data-validate="{required:true, 'validate-email':true}"/>
              </div>
            </div>
            <div class="col-sm-12 col-xs-12" style="display: none">
              <div class="form-group email required">
                <label for="comment">Comment</label>
                <textarea name="comment" id="comment" title="<?php /* @escapeNotVerified */ echo __('What’s on your mind?') ?>" class="input-text form-control" rows="4" data-validate="{required:true}">N/A</textarea>
              </div>
            </div>
          </div>
          <div class="actions-toolbar">
            <button class="action submit btn btn-primary" title="Submit" type="submit"> Submit </button>
          </div>
          </form>
        </div>
      </div>
    </div>
  </div>
<style>
h1.page-header{
   display: none;
}

   .cms-car-services .page-title-wrapper{
   padding: 0;
}

.cms-car-services .text-block h1{
   margin-bottom: 20px;
   font-size: 30px;
}

.cms-car-services .text-block h3{
   margin-bottom: 15px;
}

.cms-car-services .text-block ul{
   margin: 0 0 0 16px;
}

.cms-car-services .text-block ul li{
   list-style-type: disc;
   margin-bottom: 8px;
}

.cms-car-services .text-block.text-center{
   text-align: center;
}

.cms-car-services .images-block .image-wrap img {
    max-width: 100%;
    border: 4px double #eee;
}

table{
   width: 100%;
}

table tr td{
       padding: 8px 5px;
}

   table, th, td {
      border: 1px solid black;
   }
   td {
      text-align: center;
   }

.form-wrap{
    max-width: 70%;
    margin-left: auto;
    margin-right: auto;
    background-color: #f6f6f6;
    padding: 40px;
}

@media screen and (max-width: 767px) {
  .form-wrap{
      max-width: 100%;
  }   
  table tr td{
       padding: 4px 2px;
       font-size: 12px;
  } 
  .p-0{
  padding: 0;
}
}
</style>