<?php
/**
* Copyright © 2015 Magento. All rights reserved.
* See COPYING.txt for license details.
*/
// @codingStandardsIgnoreFile
?>
<?php
	$themeHelper = $this->helper('MGS\Mpanel\Helper\Data');
	$canUsePanel = $themeHelper->acceptToUsePanel();
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
	$store = $storeManager->getStore();
	$mediaUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
?>
<div class="contact-form-content">
	
<div class="images-block margin-bottom30">
  <div class="row">
  	<div class="col-sm-6 col-xs-12">
      <div class="image-wrap">
      	<img src="<?php echo $mediaUrl.'wysiwyg/car-services-left.jpg';?>" alt="">
      </div>
  	</div>
  		<div class="col-sm-6 col-xs-12">
        <div class="image-wrap">
      	<img src="<?php echo $mediaUrl.'wysiwyg/car-services-right-2.jpg';?>" alt="">
      </div>
		</div>
  </div>
</div>
   
<div class="content-block margin-bottom60">
  <div class="row">
  	<div class="col-sm-6 col-xs-12">
  		<div class="list">
  			<ul>
  				<li>Immediate Car Battery Replacement</li>
  				<li>Immediate Flat Tyre Services</li>
  				<li>Immediate Towing Services</li>
  				<li>Immediate Oil Change</li>
  				<li>Immediate Car Wash</li>
  			</ul>
  		</div>
  	</div>
  		<div class="col-sm-6 col-xs-12">
			<div class="right-img">
				<img src="<?php echo $mediaUrl.'wysiwyg/emergency-services.png';?>" alt="Anywhere-Anytime 24/7 Emergency Services" class="img-responsive">
			</div>
		</div>
  </div>
</div>


  <div class="form-wrap">
	<div class="row">
		<div class="col-sm-12 col-xs-12 margin-bottom60">
			<h3 class="text-uppercase margin-bottom15"><?php echo __('SEND US A MESSAGE'); ?></h3>
			<form class="form contact" action="/contact/index/post/" id="contact-form" method="post" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>" data-mage-init='{"validation":{}}'>
				<div class="row">
					<div class="col-sm-6 col-xs-12">
						<div class="form-group name required">
							<label for="name"><?php echo __('Name'); ?></label>
							<input name="name" id="name" title="<?php /* @escapeNotVerified */ echo __('Name') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text form-control" type="text" data-validate="{required:true}"/>
						</div>
					</div>
					<div class="col-sm-6 col-xs-12">
						<div class="form-group email required">
							<label for="email"><?php echo __('Email'); ?></label>
							<input name="email" id="email" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text form-control" type="email" data-validate="{required:true, 'validate-email':true}"/>
						</div>
					</div>
					<div class="col-sm-12 col-xs-12">
						<div class="form-group telephone required">
							<label for="telephone"><?php echo __('Phone'); ?></label>
							<input name="telephone" id="telephone" title="<?php /* @escapeNotVerified */ echo __('Phone') ?>" value="" class="input-text form-control" type="text" data-validate="{required:true}" />
						</div>
					</div>
					<div class="col-sm-12 col-xs-12">
						<div class="form-group location required">
							<label for="location"><?php echo __('Location'); ?></label>
							<input name="location" id="get-mylocation" title="<?php /* @escapeNotVerified */ echo __('Location') ?>" value="" class="input-text form-control" type="text" data-validate="{required:true}" />
							<input type="hidden" name="latitude" id="user-latitude" value="" />
							<input type="hidden" name="longitude" id="user-longitude" value="" />
						</div>
					</div>
					<div class="col-sm-12 col-xs-12">
						<div class="form-group comment required">
							<label for="comment"><?php echo __('Comment'); ?></label>
							<textarea name="comment" id="comment" title="<?php /* @escapeNotVerified */ echo __('What’s on your mind?') ?>" class="input-text form-control" rows="4" data-validate="{required:true}"></textarea>
						</div>
					</div>
				</div>
				<div class="actions-toolbar">
					<input type="hidden" name="hideit" id="hideit" value="" />
					<button type="submit" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>" class="action submit btn btn-primary">
					<span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
					</button>
				</div>
			</form>
		</div>
	</div>
</div>
<div class="bottom-images-block margin-bottom30 1233">
  <div class="row">
  	<div class="col-sm-3 col-xs-6">
      <div class="image-wrap">
      	<img src="https://www.tyresvision.com/media/wysiwyg/amaron-battery-1.png" alt="Amaron Battery">
      </div>
  	</div>
	<div class="col-sm-3 col-xs-6">
		<div class="image-wrap">
			<img src="https://www.tyresvision.com/media/wysiwyg/Bosh.png" alt="Bosh Battery">
		</div>
	</div>
	<div class="col-sm-3 col-xs-6">
		<div class="image-wrap">
			<img src="https://www.tyresvision.com/media/wysiwyg/solite.png" alt="Solite Battery">
		</div>
	</div>
	<div class="col-sm-3 col-xs-6">
		<div class="image-wrap">
			<img src="https://www.tyresvision.com/media/wysiwyg/Varta.png" alt="Varta Battery">
		</div>
	</div>
  </div>
</div>
</div>
<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?libraries=places&key=AIzaSyB6Hb9kbSMTp7e2wQDjcVcdGf95a_hCgFg"></script>
<script type="text/javascript">
require(['jquery', 'jquery/ui'], function($){
	jQuery( document ).ready( function($) {
		$( "#get-mylocation" ).click( function(e) {
			e.preventDefault();
			getLocation();
		});
		getLocation();
	});
	function getLocation(){
		/* Chrome need SSL! */
		var is_chrome = /chrom(e|ium)/.test( navigator.userAgent.toLowerCase() );
		var is_ssl    = 'https:' == document.location.protocol;
		if( is_chrome && ! is_ssl ){
			return false;
		}
 
		/* HTML5 Geolocation */
		navigator.geolocation.getCurrentPosition(
			function( position ){ // success cb
 
				/* Current Coordinate */
				var lat = position.coords.latitude;
				var lng = position.coords.longitude;
				var google_map_pos = new google.maps.LatLng( lat, lng );
				jQuery('#user-latitude').val(lat);
				jQuery('#user-longitude').val(lng);
				/* Use Geocoder to get address */
				var google_maps_geocoder = new google.maps.Geocoder();
				google_maps_geocoder.geocode(
					{ 'latLng': google_map_pos },
					function( results, status ) {
						if ( status == google.maps.GeocoderStatus.OK && results[0] ) {
							console.log( results[0].formatted_address );
							var locationAddress = results[0].formatted_address;
							jQuery('#get-mylocation').val(locationAddress);
						}
					}
				);
			},
			function(){ // fail cb
			}
		);
	}
});
</script>